export const userAccounts = [
  {
    id: 'user-admin',
    username: 'admin',
    displayName: '景区运营管理员',
    role: '管理员',
    status: '启用',
    passwordHash: 'sha256-demo:56760663',
    phoneMasked: '138****2026',
    createdAt: '2026-04-01 09:00',
    lastLoginAt: '2026-06-09 08:42',
    avatarColor: '#1f3a34',
  },
  {
    id: 'user-operator',
    username: 'operator',
    displayName: '票务核销员',
    role: '管理员',
    status: '启用',
    passwordHash: 'sha256-demo:56760663',
    phoneMasked: '137****0616',
    createdAt: '2026-04-08 14:20',
    lastLoginAt: '2026-06-08 17:10',
    avatarColor: '#8a6a4f',
  },
  {
    id: 'user-traveler',
    username: 'traveler',
    displayName: '普通游客账号',
    role: '普通用户',
    status: '启用',
    passwordHash: 'sha256-demo:56760663',
    phoneMasked: '136****0909',
    createdAt: '2026-04-16 19:32',
    lastLoginAt: '2026-06-01 12:05',
    avatarColor: '#7f9c8d',
  },
]

export const scenicSpots = [
  {
    id: 'west-lake',
    nameZh: '西湖风景名胜区',
    nameEn: 'West Lake Scenic Area',
    area: '西湖区 / 上城区',
    category: '湖山风景',
    description: '杭州旅行的起点。湖面、堤桥、群山与城市日常在这里安静相遇。',
    address: '杭州市西湖区龙井路1号周边',
    openingHours: '全天开放，部分点位以现场公告为准',
    tags: ['湖山', '世界遗产', '慢行'],
    reservationRequired: false,
    paid: false,
    featured: true,
    imageUrl: '/src/assets/images/scenic-west-lake.jpg',
    imagePosition: '58% 50%',
  },
  {
    id: 'lingyin-feilaifeng',
    nameZh: '灵隐飞来峰',
    nameEn: 'Lingyin Feilai Peak',
    area: '西湖区',
    category: '宋韵文脉',
    description: '飞来峰石刻、山林与灵隐片区共同构成杭州最具代表性的宋韵文化界面。',
    address: '杭州市西湖区灵隐路法云弄1号',
    openingHours: '免票开放，实行实名预约与分时游览；寺院及特殊点位以官方公告为准',
    tags: ['山林', '石刻', '寺院'],
    reservationRequired: true,
    paid: false,
    featured: true,
    imageUrl: '/src/assets/images/scenic-lingyin-feilai-feng.jpg',
    imagePosition: '52% 56%',
  },
  {
    id: 'xixi-wetland',
    nameZh: '西溪国家湿地公园',
    nameEn: 'Xixi National Wetland Park',
    area: '西湖区 / 余杭区',
    category: '湿地生态',
    description: '水网、芦荡、村落与候鸟，把杭州的另一面写得更缓慢。',
    address: '杭州市西湖区天目山路518号',
    openingHours: '开放时间、售票与最后入园以景区当日公告为准',
    tags: ['湿地', '生态', '舟行'],
    reservationRequired: true,
    paid: true,
    featured: true,
    imageUrl: '/src/assets/images/scenic-xixi-wetland.jpg',
    imagePosition: '56% 48%',
  },
  {
    id: 'liangzhu-ancient-city',
    nameZh: '良渚古城遗址公园',
    nameEn: 'Liangzhu Ancient City Ruins Park',
    area: '余杭区',
    category: '文明遗址',
    description: '在开阔的遗址公园中，阅读五千年文明留给杭州的时间厚度。',
    address: '杭州市余杭区瓶窑镇凤都路与104国道交叉口',
    openingHours: '开放时间、售票与最后入园以景区当日公告为准',
    tags: ['良渚', '遗址', '文明'],
    reservationRequired: true,
    paid: true,
    featured: true,
    imageUrl: '/src/assets/images/scenic-liangzhu-park.jpg',
    imagePosition: '50% 52%',
  },
  {
    id: 'grand-canal-hangzhou',
    nameZh: '京杭大运河杭州段',
    nameEn: 'Grand Canal Hangzhou Section',
    area: '拱墅区',
    category: '运河水岸',
    description: '桥、船、街巷与生活水岸，保留着杭州日常流动的声音。',
    address: '杭州市拱墅区拱宸桥及运河沿线',
    openingHours: '全天开放，展馆及游船以现场公告为准',
    tags: ['运河', '水岸', '街区'],
    reservationRequired: false,
    paid: false,
    featured: true,
    imageUrl: '/src/assets/images/scenic-grand-canal.jpg',
    imagePosition: '52% 54%',
  },
  {
    id: 'songcheng',
    nameZh: '宋城',
    nameEn: 'Songcheng',
    area: '西湖区',
    category: '宋韵演艺',
    description: '以宋韵、街市与演艺组织起一段更具舞台感的杭州夜游体验。',
    address: '杭州市西湖区之江路148号',
    openingHours: '开放时间、演出场次与最后入园以景区当日公告为准',
    tags: ['宋韵', '演艺', '夜游'],
    reservationRequired: true,
    paid: true,
    featured: true,
    imageUrl: '/src/assets/images/scenic-songcheng.jpg',
    imagePosition: '50% 50%',
  },
  {
    id: 'leifeng-pagoda',
    nameZh: '雷峰塔',
    nameEn: 'Leifeng Pagoda',
    area: '西湖区',
    category: '湖山风景',
    description: '从南山路边登高望湖，让传说、塔影与西湖天光重叠。',
    address: '杭州市西湖区南山路15号',
    openingHours: '开放时间、售票与最后入园以景区当日公告为准',
    tags: ['登高', '塔影', '传说'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-leifeng-pagoda.jpg',
    imagePosition: '52% 42%',
  },
  {
    id: 'hangzhou-botanical-garden',
    nameZh: '杭州植物园',
    nameEn: 'Hangzhou Botanical Garden',
    area: '西湖区',
    category: '自然园林',
    description: '在植物、溪谷和山脚之间，把城市旅行调成更低的音量。',
    address: '杭州市西湖区桃源岭1号',
    openingHours: '开放时间、售票与最后入园以园区当日公告为准',
    tags: ['植物', '山脚', '园林'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-botanical-garden.jpg',
    imagePosition: '52% 48%',
  },
  {
    id: 'hangzhou-zoo',
    nameZh: '杭州动物园',
    nameEn: 'Hangzhou Zoo',
    area: '西湖区',
    category: '亲子自然',
    description: '南山脚下的亲子自然目的地，保留着杭州人的童年记忆。',
    address: '杭州市西湖区虎跑路40号',
    openingHours: '开放时间、售票与最后入园以园区当日公告为准',
    tags: ['亲子', '自然', '城市记忆'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-zoo.jpg',
    imagePosition: '54% 46%',
  },
  {
    id: 'hu-xueyan-residence',
    nameZh: '胡雪岩故居',
    nameEn: 'Hu Xueyan Former Residence',
    area: '上城区',
    category: '历史建筑',
    description: '深宅、园林与木作细节，收纳了晚清杭州的富丽与秩序。',
    address: '杭州市上城区元宝街18号',
    openingHours: '开放时间、售票与最后入馆以场馆当日公告为准',
    tags: ['故居', '园林', '建筑'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-hu-xueyan-residence.jpg',
    imagePosition: '50% 50%',
  },
  {
    id: 'liuhetower',
    nameZh: '六和塔',
    nameEn: 'Liuhe Pagoda',
    area: '西湖区',
    category: '江岸地标',
    description: '在钱塘江边看塔与江潮，感受杭州由湖走向江的开阔。',
    address: '杭州市西湖区之江路16号',
    openingHours: '开放时间、售票与最后入园以景区当日公告为准',
    tags: ['钱塘江', '塔', '登高'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-liuhe-pagoda.jpg',
    imagePosition: '50% 50%',
  },
  {
    id: 'guozhuang',
    nameZh: '郭庄',
    nameEn: 'Guo Villa',
    area: '西湖区',
    category: '江南园林',
    description: '一座临湖园林，以更小的尺度观看西湖、花木与亭台。',
    address: '杭州市西湖区杨公堤28号',
    openingHours: '开放时间、售票与最后入园以园区当日公告为准',
    tags: ['园林', '临湖', '小景'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-guozhuang.jpg',
    imagePosition: '54% 52%',
  },
  {
    id: 'xiaohe-street',
    nameZh: '小河直街',
    nameEn: 'Xiaohe Straight Street',
    area: '拱墅区',
    category: '历史街区',
    description: '白墙、木窗与运河支流，让杭州的烟火气保留在窄街水岸。',
    address: '杭州市拱墅区小河直街历史文化街区',
    openingHours: '全天开放，商户时间各异',
    tags: ['街区', '运河', '日常'],
    reservationRequired: false,
    paid: false,
    featured: false,
    imageUrl: '/src/assets/images/scenic-xiaohe-street.jpg',
    imagePosition: '54% 56%',
  },
  {
    id: 'southern-song-imperial-street',
    nameZh: '南宋御街',
    nameEn: 'Southern Song Imperial Street',
    area: '上城区',
    category: '宋韵文脉',
    description: '从街巷肌理里看南宋临安的历史层次与当代生活。',
    address: '杭州市上城区中山中路沿线',
    openingHours: '全天开放，展馆及商户时间各异',
    tags: ['宋韵', '街区', '历史'],
    reservationRequired: false,
    paid: false,
    featured: false,
    imageUrl: '/src/assets/images/scenic-southern-song-street.jpg',
    imagePosition: '52% 44%',
  },
  {
    id: 'xianghu',
    nameZh: '湘湖',
    nameEn: 'Xianghu Lake',
    area: '萧山区',
    category: '湖山风景',
    description: '比西湖更开阔安静的水面，适合把旅行节奏放得更慢。',
    address: '杭州市萧山区湘湖路132号周边',
    openingHours: '全天开放，部分场馆以现场公告为准',
    tags: ['湖泊', '慢行', '亲水'],
    reservationRequired: false,
    paid: false,
    featured: false,
    imageUrl: '/src/assets/images/scenic-xianghu.jpg',
    imagePosition: '50% 50%',
  },
  {
    id: 'qiandao-lake',
    nameZh: '千岛湖',
    nameEn: 'Qiandao Lake',
    area: '淳安县',
    category: '湖岛度假',
    description: '从城市向西南抵达更大的水面，在群岛之间展开杭州的远行面。',
    address: '杭州市淳安县千岛湖镇梦姑路',
    openingHours: '开放时间、船班与最后入园以景区当日公告为准',
    tags: ['湖岛', '远行', '度假'],
    reservationRequired: true,
    paid: true,
    featured: false,
    imageUrl: '/src/assets/images/scenic-qiandao-lake.jpg',
    imagePosition: '50% 50%',
  },
]

export const ticketTypes = [
  {
    id: 'west-lake-free',
    scenicSpotId: 'west-lake',
    name: '免费入园登记',
    price: 0,
    description: '开放式湖区免费参观，节假日客流、安检与交通组织以现场公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'lingyin-free',
    scenicSpotId: 'lingyin-feilaifeng',
    name: '免费入园登记',
    price: 0,
    description: '飞来峰景区已实行免票开放；寺院、活动及特殊点位以官方公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'xixi-adult',
    scenicSpotId: 'xixi-wetland',
    name: '成人票',
    price: 80,
    description: '西溪湿地公园基础门票，游船及联票以官方票务渠道实时规则为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'liangzhu-adult',
    scenicSpotId: 'liangzhu-ancient-city',
    name: '成人票',
    price: 60,
    description: '良渚古城遗址公园基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'songcheng-adult',
    scenicSpotId: 'songcheng',
    name: '成人票',
    price: 300,
    description: '宋城演艺门票，具体演出场次、座席与退改规则以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'xixi-child',
    scenicSpotId: 'xixi-wetland',
    name: '儿童票',
    price: 40,
    description: '儿童优惠票，适用年龄、身高与证件要求以官方票务渠道为准。',
    availableFor: '儿童游客',
  },
  {
    id: 'liangzhu-senior',
    scenicSpotId: 'liangzhu-ancient-city',
    name: '老人票',
    price: 0,
    description: '老人优待凭证，入园时请携带可核验的有效证件。',
    availableFor: '符合优待条件游客',
  },
  {
    id: 'canal-free',
    scenicSpotId: 'grand-canal-hangzhou',
    name: '免费入园登记',
    price: 0,
    description: '运河公共水岸免费开放，展馆、游船与活动票务以官方公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'songcheng-child',
    scenicSpotId: 'songcheng',
    name: '儿童票',
    price: 180,
    description: '宋城儿童优惠票，适用范围以官方票务渠道为准。',
    availableFor: '儿童游客',
  },
  {
    id: 'leifeng-adult',
    scenicSpotId: 'leifeng-pagoda',
    name: '成人票',
    price: 40,
    description: '雷峰塔基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'botanical-adult',
    scenicSpotId: 'hangzhou-botanical-garden',
    name: '成人票',
    price: 10,
    description: '杭州植物园基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'zoo-adult',
    scenicSpotId: 'hangzhou-zoo',
    name: '成人票',
    price: 20,
    description: '杭州动物园基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'hu-residence-adult',
    scenicSpotId: 'hu-xueyan-residence',
    name: '成人票',
    price: 20,
    description: '胡雪岩故居基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'liuhetower-adult',
    scenicSpotId: 'liuhetower',
    name: '成人票',
    price: 20,
    description: '六和塔基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'guozhuang-adult',
    scenicSpotId: 'guozhuang',
    name: '成人票',
    price: 10,
    description: '郭庄基础门票，优惠与免票政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
  {
    id: 'xiaohe-free',
    scenicSpotId: 'xiaohe-street',
    name: '免费入园登记',
    price: 0,
    description: '小河直街开放街区免费参观，商户营业与活动安排以现场公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'southern-song-free',
    scenicSpotId: 'southern-song-imperial-street',
    name: '免费入园登记',
    price: 0,
    description: '南宋御街开放街区免费参观，展馆与商户营业安排以现场公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'xianghu-free',
    scenicSpotId: 'xianghu',
    name: '免费入园登记',
    price: 0,
    description: '湘湖公共湖区免费参观，部分场馆、游船与活动票务以官方公告为准。',
    availableFor: '全体游客',
  },
  {
    id: 'qiandao-adult',
    scenicSpotId: 'qiandao-lake',
    name: '成人票',
    price: 150,
    description: '千岛湖中心湖区基础门票，船班、联票与优惠政策以官方票务渠道为准。',
    availableFor: '18周岁及以上游客',
  },
]

const reservableSpotIds = [
  'west-lake',
  'lingyin-feilaifeng',
  'xixi-wetland',
  'liangzhu-ancient-city',
  'grand-canal-hangzhou',
  'songcheng',
  'leifeng-pagoda',
  'hangzhou-botanical-garden',
  'hangzhou-zoo',
  'hu-xueyan-residence',
  'liuhetower',
  'guozhuang',
  'xiaohe-street',
  'southern-song-imperial-street',
  'xianghu',
  'qiandao-lake',
]

export const timeRanges = ['09:00-11:00', '11:00-13:00', '14:00-16:00']

const hangzhouDateParts = (date = new Date()) => {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(date)

  return Object.fromEntries(parts.map((part) => [part.type, part.value]))
}

export const todayInHangzhou = () => {
  const parts = hangzhouDateParts()
  return `${parts.year}-${parts.month}-${parts.day}`
}

const baseDate = new Date(`${todayInHangzhou()}T00:00:00+08:00`)
const toDateString = (offset) => {
  const date = new Date(baseDate)
  date.setDate(baseDate.getDate() + offset)
  const pad = (value) => String(value).padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
}

export const bookingSlots = reservableSpotIds.flatMap((scenicSpotId, spotIndex) =>
  Array.from({ length: 7 }, (_, dayIndex) =>
    timeRanges.map((timeRange, timeIndex) => {
      const capacity = 80 + ((spotIndex + timeIndex) % 4) * 30
      const booked = 18 + ((spotIndex * 17 + dayIndex * 13 + timeIndex * 19) % (capacity - 22))

      return {
        id: `${scenicSpotId}-${dayIndex + 1}-${timeIndex + 1}`,
        scenicSpotId,
        date: toDateString(dayIndex),
        timeRange,
        capacity,
        booked,
      }
    }),
  ).flat(),
)

const seededOrderSlot = bookingSlots.find((slot) => slot.id === 'west-lake-1-1')

export const bookingOrders = [
  {
    id: 'HZ-20260609-0001',
    scenicSpotId: 'west-lake',
    slotId: 'west-lake-1-1',
    userId: 'user-traveler',
    ticketName: '免费入园登记',
    spotName: '西湖风景名胜区',
    visitDate: seededOrderSlot?.date ?? todayInHangzhou(),
    timeRange: seededOrderSlot?.timeRange ?? '09:00-11:00',
    visitors: ['李然', '李小满'],
    status: '待出行',
    paymentMethod: 'free',
    paymentStatus: '免费预约',
    amount: 0,
    visitorCount: 2,
    qrCodeText: 'VERIFY-HZ-20260609-0001',
    createdAt: '2026-06-09 08:42',
    contactPhone: '+86 136 8800 2110',
    contactEmail: 'liran.family@example.com',
    maskedIdNumber: '3301********0211',
    refundStatus: '无需退款',
    supportHotline: '12301',
    supportEmail: 'tickets@hangzhou.example.gov.cn',
    appealStatus: '可发起',
    invoiceStatus: '可申请',
  },
]

export const auditLogs = [
  {
    id: 'audit-20260609-001',
    actor: 'admin',
    role: '管理员',
    action: '初始化数据',
    targetTable: 'database',
    targetId: 'hangzhou.sqlite',
    detail: '创建本地 SQLite 数据库并写入种子数据。',
    createdAt: '2026-06-09 08:42',
  },
]

export const cityPassPrices = new Map([
  ['west-lake-day-pass', 168],
  ['song-heritage-pass', 198],
  ['family-nature-pass', 228],
  ['canal-night-transit-pass', 138],
])
