import type { LocalizedList, LocalizedText } from '../i18n/site'

const text = (zh: string, en: string, ja: string, ko: string): LocalizedText => ({
  'zh-CN': zh,
  'en-US': en,
  'ja-JP': ja,
  'ko-KR': ko,
})

const list = (zh: string[], en: string[], ja: string[], ko: string[]): LocalizedList => ({
  'zh-CN': zh,
  'en-US': en,
  'ja-JP': ja,
  'ko-KR': ko,
})

export type PracticalVisitGuide = {
  duration: LocalizedText
  bestArrival: LocalizedText
  peakAvoidance: LocalizedText
  bestFor: LocalizedList
  photoSpots: LocalizedList
  nearbyDining: LocalizedList
  restrooms: LocalizedText
  storage: LocalizedText
  rainyPlan: LocalizedText
  languageService: LocalizedText
}

export const practicalGuideLabels = {
  sectionEyebrow: text(
    '实用出行判断',
    'Practical Planning',
    '実用的な訪問判断',
    '실용 방문 판단',
  ),
  sectionTitle: text('行前决策信息', 'Visit Decision Guide', '訪問判断ガイド', '방문 판단 가이드'),
  duration: text('建议游玩时长', 'Suggested Duration', '目安滞在時間', '권장 체류 시간'),
  bestArrival: text('最佳到达时间', 'Best Arrival Time', 'おすすめ到着時間', '추천 도착 시간'),
  peakAvoidance: text('旺季避峰建议', 'Peak-Avoidance Tip', '繁忙期の回避ポイント', '성수기 혼잡 회피 팁'),
  bestFor: text('适合人群', 'Best For', '向いている人', '추천 방문객'),
  photoSpots: text('推荐拍照点', 'Photo Spots', '撮影ポイント', '추천 촬영 포인트'),
  nearbyDining: text('附近餐饮', 'Nearby Dining', '周辺の食事', '주변 식음'),
  restrooms: text('厕所', 'Restrooms', 'トイレ', '화장실'),
  storage: text('寄存', 'Storage', '荷物預かり', '보관'),
  rainyPlan: text('雨天方案', 'Rainy-Day Plan', '雨天プラン', '우천 대안'),
  languageService: text('语言服务', 'Language Support', '言語サポート', '언어 지원'),
}

const practicalGuides: Record<string, PracticalVisitGuide> = {
  'west-lake': {
    duration: text(
      '建议预留 2 至 4 小时；若串联断桥、白堤、湖滨与雷峰塔，建议安排半天。',
      'Set aside 2 to 4 hours; allow half a day if you are linking Broken Bridge, Bai Causeway, Hubin and Leifeng Pagoda.',
      '目安は2〜4時間。断橋、白堤、湖浜、雷峰塔まで回るなら半日あると安心です。',
      '2~4시간 정도가 적당하며, 단교와 백제, 후빈, 레이펑타까지 함께 보면 반나절이 좋습니다.',
    ),
    bestArrival: text(
      '晴天建议 8:00 前到断桥或湖滨一带，光线柔和、步道也更轻松。',
      'On clear days, arrive around Broken Bridge or Hubin before 8:00 for softer light and lighter foot traffic.',
      '晴天は8時前に断橋または湖浜周辺へ。光が柔らかく、人の流れもまだ穏やかです。',
      '맑은 날에는 오전 8시 전 단교나 후빈 일대 도착이 좋습니다. 빛이 부드럽고 동선도 한결 여유롭습니다.',
    ),
    peakAvoidance: text(
      '法定节假日尽量避开 10:00 至 16:00 的断桥、白堤与湖滨主线，改走杨公堤、郭庄或傍晚湖西线更舒展。',
      'During public holidays, avoid Broken Bridge, Bai Causeway and Hubin from 10:00 to 16:00; Yang Causeway, Guo Villa and the west lakeside are calmer toward evening.',
      '祝日は10時〜16時の断橋、白堤、湖浜メインルートを避け、楊公堤や郭荘、西湖西側を夕方に回ると余裕があります。',
      '공휴일에는 10:00~16:00 단교, 백제, 후빈 메인 구간을 피하고 양공제나 궈좡, 서호 서측을 늦은 오후에 도는 편이 좋습니다.',
    ),
    bestFor: list(
      ['第一次来杭州的游客', '城市慢行与拍照人群', '亲子或长辈同行的宽松行程'],
      ['First-time visitors to Hangzhou', 'Slow walkers and photo-focused visitors', 'Easy family trips with children or older companions'],
      ['杭州が初めての人', '散策と写真を楽しみたい人', '子どもや年配者とゆったり回りたい人'],
      ['항저우 첫 방문객', '산책과 사진 중심 방문객', '아이·어르신과 여유 있게 다니는 일정'],
    ),
    photoSpots: list(
      ['断桥北侧晨景', '白堤临水树影', '长桥公园远望雷峰塔'],
      ['Morning light from the north side of Broken Bridge', 'Tree reflections along Bai Causeway', 'Leifeng Pagoda seen from Changqiao Park'],
      ['断橋北側の朝景', '白堤の水辺の樹影', '長橋公園から望む雷峰塔'],
      ['단교 북측 아침 풍경', '백제 수변의 나무 그림자', '창차오공원에서 보는 레이펑타'],
    ),
    nearbyDining: list(
      ['湖滨步行区简餐与茶饮', '南山路沿线杭帮菜', '龙井茶村茶席与农家菜'],
      ['Casual dining and tea in Hubin', 'Hangzhou cuisine along Nanshan Road', 'Tea service and farmhouse dishes in Longjing tea village'],
      ['湖浜エリアの軽食とティー', '南山路沿いの杭州料理', '龍井茶村の茶席と農家料理'],
      ['후빈 보행구의 간단한 식사와 차', '난산로 일대 항저우 요리', '룽징 차마을 다석과 농가 음식'],
    ),
    restrooms: text(
      '断桥、湖滨游客服务点、白堤主要节点与公园入口附近均有公厕，旺季建议见到就先用。',
      'Public restrooms are available near Broken Bridge, Hubin service points, major Bai Causeway nodes and park entrances; in peak periods, use them when you see them.',
      '断橋、湖浜のサービス拠点、白堤の主要ポイント、公園入口付近に公衆トイレがあります。繁忙期は見つけたら早めの利用がおすすめです。',
      '단교, 후빈 서비스 포인트, 백제 주요 지점, 공원 입구 주변에 화장실이 있습니다. 성수기에는 보이면 미리 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '景区整体不以集中寄存为主，可优先使用酒店、地铁枢纽或大型商场服务台附近的寄存设施。',
      'The scenic area does not rely on one central luggage room; hotel storage, metro hubs and larger retail service counters are the safer options.',
      '景区全体として大きな一括荷物預かりは少なめです。ホテル、地下鉄ターミナル、大型商業施設の預かりを優先してください。',
      '경구 전체에 중앙 보관소가 있는 형태는 아닙니다. 호텔, 지하철 환승 거점, 대형 상업시설 보관 서비스를 우선 이용하는 편이 안전합니다.',
    ),
    rainyPlan: text(
      '小雨适合保留湖滨短线与博物馆、茶室组合；大雨时建议改为中国丝绸博物馆、南山路展馆等室内内容。',
      'In light rain, keep a shorter Hubin walk and pair it with museums or teahouses; in heavier rain, switch to indoor options such as the China National Silk Museum and nearby galleries.',
      '小雨なら湖浜の短い散策に博物館や茶室を組み合わせるのがおすすめ。強い雨なら中国シルク博物館や南山路周辺の屋内施設へ切り替えてください。',
      '가벼운 비라면 후빈 짧은 산책에 박물관이나 찻집을 묶는 편이 좋고, 큰비에는 중국실크박물관 같은 실내 코스로 전환하는 것이 좋습니다.',
    ),
    languageService: text(
      '湖滨与主要游客节点的中英双语指引相对完整，热门码头与游客中心更容易获得英文协助。',
      'Chinese-English wayfinding is comparatively strong around Hubin and the main visitor nodes, with the best support near popular piers and visitor centres.',
      '湖浜と主要な観光拠点では中英表記が比較的整っており、人気の船着場や案内所で英語サポートを受けやすいです。',
      '후빈과 주요 관광 거점은 중영문 안내가 비교적 잘 갖춰져 있고, 인기 선착장과 안내소에서 영어 도움을 받기 쉽습니다.',
    ),
  },
  'lingyin-feilaifeng': {
    duration: text(
      '建议安排 2 至 3.5 小时；若包含灵隐寺、飞来峰石刻和法云古村，建议半天。',
      'Plan for 2 to 3.5 hours, or half a day if including Lingyin Temple, the cliff carvings and Fayun Ancient Village.',
      '2〜3.5時間が目安。霊隠寺、飛来峰石刻、法雲古村まで回るなら半日あると安心です。',
      '2~3.5시간 정도가 적당하며, 링인사와 페이라이펑 석각, 파윈 마을까지 보면 반나절이 좋습니다.',
    ),
    bestArrival: text(
      '建议开园后尽早进入，9:00 前山门与主线步道体感最好。',
      'Enter as early as practical after opening; before 9:00 the main gate and principal paths are most comfortable.',
      '開園後なるべく早めの入場がおすすめです。9時前なら山門と主動線が最も回りやすいです。',
      '개장 후 가능한 빨리 입장하는 편이 좋고, 9시 전이 정문과 메인 동선이 가장 쾌적합니다.',
    ),
    peakAvoidance: text(
      '周末与香期尽量避开 10:00 之后的主入口排队，优先工作日上午或雨后时段。',
      'On weekends and incense-heavy dates, avoid the main entrance queue after 10:00; weekday mornings and the period after rain are easier.',
      '週末や参拝客の多い日は10時以降の正門待ちを避け、平日の午前や雨上がりを優先すると回りやすいです。',
      '주말과 향객이 많은 날은 10시 이후 정문 대기를 피하고, 평일 오전이나 비 갠 뒤 시간대를 우선하는 편이 낫습니다.',
    ),
    bestFor: list(
      ['历史文化与宗教建筑爱好者', '第一次来杭州想看代表性宋韵景观的游客', '愿意步行爬坡的旅行者'],
      ['Visitors interested in history, religion and architecture', 'First-time visitors seeking a signature Song-heritage stop', 'Travellers comfortable with uphill walking'],
      ['歴史文化や宗教建築に関心のある人', '杭州らしい宋韻景観を見たい初訪問者', '坂道歩きに無理のない人'],
      ['역사·종교 건축에 관심 있는 방문객', '대표적인 송풍 경관을 보고 싶은 첫 방문객', '오르막 보행이 가능한 여행자'],
    ),
    photoSpots: list(
      ['飞来峰石刻近景', '冷泉桥与溪涧', '法云路竹林与白墙'],
      ['Close views of the Feilai Peak carvings', 'Lengquan Bridge and streamside paths', 'Bamboo and white walls along Fayun Road'],
      ['飛来峰石刻の近景', '冷泉橋と渓流', '法雲路の竹林と白壁'],
      ['페이라이펑 석각 근경', '렁취안차오와 계류', '파윈로의 대숲과 흰 벽'],
    ),
    nearbyDining: list(
      ['灵隐路沿线素斋与简餐', '法云古村茶席与小馆', '景区外围游客中心轻食'],
      ['Vegetarian meals and casual dining along Lingyin Road', 'Tea service and small restaurants in Fayun village', 'Light meals near the outer visitor centre'],
      ['霊隠路沿いの精進料理と軽食', '法雲古村の茶席と小さな食堂', '景区外側の案内拠点周辺の軽食'],
      ['링인로 일대 채식·간단식', '파윈 마을 다석과 작은 식당', '외곽 관광안내 거점 주변의 간편식'],
    ),
    restrooms: text(
      '游客中心、飞来峰入口、寺院外侧与法云古村主线均能找到公厕，山林段请提前规划。',
      'Restrooms are available at the visitor centre, Feilai Peak entrance, outside the temple and along Fayun village; plan ahead before entering the wooded sections.',
      '案内所、飛来峰入口、寺院外側、法雲古村の主動線にトイレがあります。山林区間に入る前に済ませておくと安心です。',
      '안내소, 페이라이펑 입구, 사찰 외곽, 파윈 마을 메인 동선에 화장실이 있습니다. 숲길 구간에 들어가기 전 미리 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '可询问游客中心或安检附近的临时寄存安排；不建议携带过大行李进入山路与台阶区域。',
      'Ask the visitor centre or security area about temporary storage; oversized luggage is best avoided on the mountain paths and steps.',
      '一時預かりは案内所や手荷物検査付近で確認してください。山道や階段が多いため、大きな荷物は持ち込みを避けるのが無難です。',
      '임시 보관은 안내소나 보안 검색 주변에서 확인할 수 있습니다. 산길과 계단이 많아 큰 짐은 가져가지 않는 편이 좋습니다.',
    ),
    rainyPlan: text(
      '小雨时石刻与林间氛围更好，但山路和石阶会打滑；大雨建议缩短山路，转为寺院外廊、法云村慢行。',
      'Light rain improves the mood of the carvings and woods, but paths and stone steps get slippery; in heavier rain, shorten the hillside route and focus on covered temple edges and Fayun village.',
      '小雨は石刻や林の雰囲気を引き立てますが、石段は滑りやすくなります。大雨なら山道を短くして、寺院の回廊や法雲村中心に切り替えてください。',
      '가벼운 비는 석각과 숲 분위기를 살리지만 돌계단이 미끄럽습니다. 큰비에는 산길을 줄이고 사찰 회랑과 파윈 마을 중심으로 바꾸는 편이 좋습니다.',
    ),
    languageService: text(
      '主要导视与售检票区域通常有中英信息，深度讲解以中文为主，建议提前准备英文音频或图文资料。',
      'Main wayfinding and ticket checkpoints usually provide Chinese-English information; deeper interpretation remains mostly Chinese, so preloaded English audio or reading material helps.',
      '主要な案内とチケット動線では中英表記が見込めますが、詳しい解説は中国語中心です。英語音声や資料を事前に用意すると安心です。',
      '주요 안내와 매표·검표 구역은 중영문 정보가 비교적 있으나, 깊은 해설은 중국어 중심이라 영어 오디오나 자료를 미리 준비하면 좋습니다.',
    ),
  },
  'xixi-wetland': {
    duration: text(
      '建议预留 3 至 5 小时；若加船线、观鸟或茶歇，可直接安排半天到一天。',
      'Allow 3 to 5 hours, or half a day to a full day if you are adding boat routes, birding or longer tea breaks.',
      '3〜5時間が目安。舟移動や野鳥観察、茶休憩を入れるなら半日から1日見ておくと安心です。',
      '3~5시간이 기본이며, 배 이동이나 철새 관찰, 긴 휴식을 넣으면 반나절에서 하루까지 잡는 편이 좋습니다.',
    ),
    bestArrival: text(
      '建议开园后尽早入园，早晨光线柔和、气温更适合步行，船线也更从容。',
      'Arrive soon after opening for softer light, easier walking temperatures and more relaxed boat timing.',
      '開園後の早い時間がおすすめです。光がやわらかく、歩きやすく、舟の時間にも余裕が出ます。',
      '개장 직후 입장이 좋습니다. 빛이 부드럽고 걷기 좋은 기온이며, 배 시간도 더 여유롭습니다.',
    ),
    peakAvoidance: text(
      '节假日中午至下午早段的周家村入口与热门船线最拥挤，建议先走湿地深处再回主入口。',
      'From midday into early afternoon on holidays, Zhoujiacun entrance and the popular boat routes are busiest; start deeper in the wetland and return later to the main gate.',
      '祝日の昼前後は周家村入口と人気の舟ルートが最も混みます。先に奥へ進み、あとでメイン入口へ戻る順が回りやすいです。',
      '공휴일 한낮에는 저우자춘 입구와 인기 배 노선이 가장 붐빕니다. 먼저 습지 안쪽으로 들어갔다가 나중에 메인 입구로 돌아오는 편이 좋습니다.',
    ),
    bestFor: list(
      ['喜欢自然、舟行与慢节奏的人', '亲子与观鸟爱好者', '想避开传统热门景点密集人流的游客'],
      ['Nature lovers and slow travellers', 'Families and birdwatchers', 'Visitors wanting a calmer alternative to the busiest headline spots'],
      ['自然や舟遊び、ゆったりした旅が好きな人', '家族連れや野鳥観察が好きな人', '定番スポットの大混雑を避けたい人'],
      ['자연과 수상 이동, 느린 여행을 좋아하는 사람', '가족 단위와 조류 관찰 방문객', '대표 명소의 밀집 인파를 피하고 싶은 여행자'],
    ),
    photoSpots: list(
      ['河渚街水巷', '深潭口木栈道', '芦苇荡与摇橹船同框点'],
      ['Canal lanes around Hezhu Street', 'Boardwalks near Shentankou', 'Reed beds with sculling boats in frame'],
      ['河渚街の水辺の路地', '深潭口の木道', '葦原と手漕ぎ舟を一緒に撮れるポイント'],
      ['허주 거리 수로 골목', '선탄커우 목재 데크', '갈대밭과 노 젓는 배를 함께 담는 포인트'],
    ),
    nearbyDining: list(
      ['河渚街小吃与本地菜', '湿地入口周边茶饮与简餐', '蒋村慢生活街区餐饮'],
      ['Snacks and local dishes on Hezhu Street', 'Tea and light meals near the wetland entrances', 'Dining options in the Jiangcun area'],
      ['河渚街の軽食と郷土料理', '湿地入口周辺のティーと軽食', '蒋村エリアの飲食店'],
      ['허주 거리 간식과 현지식', '습지 입구 주변 차와 간편식', '장춘 지역 식당가'],
    ),
    restrooms: text(
      '入口服务区、船码头、河渚街与主要步道节点都有公厕，深线步行前建议先补给。',
      'Restrooms are available at entrance service zones, boat piers, Hezhu Street and major walkway nodes; use one before longer inner wetland walks.',
      '入口サービス区、船着場、河渚街、主要な遊歩道の結節点にトイレがあります。奥へ歩く前に利用しておくと安心です。',
      '입구 서비스 구역, 선착장, 허주 거리, 주요 보행 결절점에 화장실이 있습니다. 안쪽으로 오래 걸어 들어가기 전 미리 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '游客中心周边可先询问寄存安排；园区步行距离长，推车和小件背包更适合。',
      'Ask around the visitor centre for storage options first; because walking distances are long, strollers and smaller day bags work better than large luggage.',
      '荷物預かりはまず案内所周辺で確認してください。歩行距離が長いため、大きな荷物よりベビーカーや小さめのデイバッグ向きです。',
      '짐 보관은 우선 안내소 주변에서 확인하세요. 도보 거리가 길어 큰 캐리어보다 유모차나 작은 데이백이 더 적합합니다.',
    ),
    rainyPlan: text(
      '小雨对湿地氛围友好，但木栈道会湿滑；大雨建议减少乘船和深线步行，集中在入口街区与室内展陈。',
      'Light rain suits the wetland atmosphere, but boardwalks become slick; in heavier rain, reduce boat use and deep-route walking, and stay closer to entrance streets and indoor displays.',
      '小雨は湿地の雰囲気に合いますが、木道は滑りやすくなります。大雨なら乗船や奥の散策を減らし、入口街区や屋内展示中心にしてください。',
      '가벼운 비는 습지 분위기에 잘 맞지만 목재 데크가 미끄럽습니다. 큰비에는 배와 깊숙한 동선을 줄이고 입구 거리와 실내 전시 위주로 보는 편이 좋습니다.',
    ),
    languageService: text(
      '主要售检票与导览图通常可见中英信息，若计划乘船或深入湿地区，建议提前截图路线。',
      'Chinese-English information is usually available at key ticketing points and maps, but if you plan to take boats or go deep into the wetlands, save route screenshots in advance.',
      '主要な券売・案内図では中英表記が見込めますが、乗船や湿地深部まで回るならルートを事前保存しておくと安心です。',
      '주요 매표·안내 지도에는 중영문 정보가 비교적 있으나, 배를 타거나 안쪽까지 들어갈 계획이면 경로를 미리 저장해 두는 편이 좋습니다.',
    ),
  },
  'liangzhu-ancient-city': {
    duration: text(
      '建议安排 3 至 4.5 小时；若含博物院与遗址公园联动，建议完整半天。',
      'Plan for 3 to 4.5 hours, or a full half day if combining the museum and the ruins park.',
      '3〜4.5時間が目安。博物院と遺跡公園を合わせるなら、しっかり半日取るのがおすすめです。',
      '3~4.5시간이 적당하며, 박물관과 유적공원을 함께 보면 반나절을 온전히 잡는 편이 좋습니다.',
    ),
    bestArrival: text(
      '建议上午到达，日照更温和，也更适合先看遗址再进展陈。',
      'Morning arrival is best, with softer sun and a smoother order of ruins first, exhibitions after.',
      '午前の到着がおすすめです。日差しが穏やかで、遺跡を見てから展示へ入る流れが組みやすいです。',
      '오전 도착이 좋습니다. 햇빛이 덜 강하고, 유적을 먼저 보고 전시로 들어가는 흐름이 자연스럽습니다.',
    ),
    peakAvoidance: text(
      '暑期与长假中午暴晒和接驳排队都明显，建议避开 11:30 至 15:00 的开阔地段。',
      'Summer and long holidays bring strong midday sun and shuttle queues; avoid the exposed sections from 11:30 to 15:00.',
      '夏季や連休は昼の強い日差しとシャトル待ちが目立ちます。11:30〜15:00 の開けた区間はなるべく避けてください。',
      '여름과 연휴에는 한낮 직사광선과 셔틀 대기가 두드러집니다. 11:30~15:00 개방 구간은 가능한 피하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['考古、文明遗址与博物馆爱好者', '研学与家庭教育出行', '愿意看展和步行结合的旅行者'],
      ['Visitors interested in archaeology and civilisation', 'Educational family trips', 'Travellers happy to combine exhibitions with open-air walking'],
      ['考古や文明遺跡、博物館が好きな人', '学びを伴う家族旅行', '展示鑑賞と屋外散策を両方楽しみたい人'],
      ['고고학·문명 유적·박물관에 관심 있는 사람', '교육형 가족 여행', '전시 관람과 야외 보행을 함께 하고 싶은 여행자'],
    ),
    photoSpots: list(
      ['城墙遗址开阔草坡', '水利系统遗址视角', '低饱和大地景观与步道'],
      ['Open grassy slopes near the wall remains', 'Views across the ancient waterworks', 'Muted earth-toned landscapes and walkways'],
      ['城壁遺構の広い草地', '水利遺構を見渡す視点', '低彩度の大地景観と遊歩道'],
      ['성벽 유구 주변의 넓은 초지', '수리 유적을 내려다보는 시점', '저채도 대지 풍경과 산책로'],
    ),
    nearbyDining: list(
      ['博物院与游客中心周边简餐', '瓶窑镇本地餐馆', '园区外轻食与咖啡'],
      ['Light meals around the museum and visitor centre', 'Local restaurants in Pingyao town', 'Casual cafes outside the park'],
      ['博物院や案内所周辺の軽食', '瓶窯鎮のローカルレストラン', '園外のカフェや軽食'],
      ['박물관·안내소 주변 간단식', '핑야오 진 현지 식당', '공원 바깥의 카페와 가벼운 식사'],
    ),
    restrooms: text(
      '游客中心、博物院与主要接驳点附近配置较稳定，进入开阔遗址步行段前建议先停留补给。',
      'Restrooms are reliably placed near the visitor centre, museum and main shuttle nodes; use them before the more exposed ruins walk.',
      '案内所、博物院、主要なシャトル拠点付近では比較的安定してトイレを見つけられます。開けた遺跡区間に入る前に利用するのがおすすめです。',
      '안내소, 박물관, 주요 셔틀 거점 근처에 화장실 배치가 비교적 안정적입니다. 넓게 트인 유적 구간에 들어가기 전 미리 이용하세요.',
    ),
    storage: text(
      '可优先咨询游客中心；园区尺度较大，不建议带过重行李在遗址步道间移动。',
      'Check with the visitor centre first; because the park is spread out, heavy luggage is not practical on the ruins paths.',
      '荷物預かりはまず案内所へ。園内は広いため、重い荷物を持って遺跡歩道を移動するのはあまり向きません。',
      '짐 보관은 우선 안내소에 문의하세요. 공원이 넓어 무거운 짐을 들고 유적 산책로를 다니기에는 적합하지 않습니다.',
    ),
    rainyPlan: text(
      '雨天时建议提高博物院权重、缩短遗址外圈步行；若遇持续大雨，可转为室内讲解与展陈为主。',
      'In rain, give more weight to the museum and shorten the outer ruins walk; in sustained rain, make it primarily an indoor interpretation visit.',
      '雨の日は博物院の比重を上げ、遺跡の外周歩行は短めに。強い雨が続くなら屋内展示中心へ切り替えるのが無難です。',
      '비 오는 날에는 박물관 비중을 높이고 외곽 유적 보행은 줄이세요. 계속 큰비가 오면 실내 전시 중심으로 바꾸는 편이 좋습니다.',
    ),
    languageService: text(
      '世界遗产相关点位通常更容易看到中英基础信息，但更深入的文明脉络建议搭配英文资料阅读。',
      'World Heritage-related nodes more often include basic Chinese-English information, but deeper civilisation context is easier with supporting English reading.',
      '世界遺産関連の拠点では中英の基礎情報を見つけやすい一方、文明史の深い理解には英語資料を併用すると安心です。',
      '세계유산 관련 거점은 중영문 기초 정보가 비교적 잘 보이지만, 더 깊은 문명 맥락은 영어 자료를 함께 보는 편이 좋습니다.',
    ),
  },
  'grand-canal-hangzhou': {
    duration: text(
      '建议安排 2 至 4 小时；若加博物馆、夜游或运河步行，可延长到半天。',
      'Allow 2 to 4 hours, or half a day if adding museums, night views or a longer canal walk.',
      '2〜4時間が目安。博物館、夜景、運河散策を加えるなら半日あるとちょうどよいです。',
      '2~4시간이 적당하며, 박물관이나 야경, 운하 산책을 더하면 반나절이 좋습니다.',
    ),
    bestArrival: text(
      '16:30 后到达更适合，一次兼顾白天街区与夜间亮灯水岸。',
      'Arriving after about 16:30 works well, letting you see both daytime streets and illuminated evening watersides.',
      '16:30以降の到着が回りやすく、昼の街並みと夜のライトアップ水辺を一度に楽しめます。',
      '16:30 이후 도착이 좋습니다. 낮의 거리와 밤의 조명 수변을 한 번에 볼 수 있습니다.',
    ),
    peakAvoidance: text(
      '周末晚间的拱宸桥与桥西街区人流最集中，建议错开 19:00 至 21:00 的桥头主节点。',
      'On weekend evenings, Gongchen Bridge and Qiaoxi are the busiest; avoid the main bridgehead area from 19:00 to 21:00.',
      '週末夜は拱宸橋と橋西街区に人が集中します。19時〜21時の橋詰め付近は時間をずらすと快適です。',
      '주말 저녁에는 궁천교와 차오시 구역에 인파가 몰립니다. 19:00~21:00 다리 입구 메인 구간은 피하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['喜欢城市步行与街区观察的人', '夜游和拍照人群', '想把博物馆与餐饮串起来的游客'],
      ['Urban walkers and neighbourhood observers', 'Night-view and photography visitors', 'Travellers combining museums with dining'],
      ['街歩きや街区観察が好きな人', '夜景と写真を楽しみたい人', '博物館と食事を組み合わせたい人'],
      ['도시 산책과 골목 관찰을 좋아하는 사람', '야경·사진 중심 방문객', '박물관과 식사를 함께 묶고 싶은 여행자'],
    ),
    photoSpots: list(
      ['拱宸桥桥面与桥下水位', '桥西历史街区夜灯', '运河步道与游船同框'],
      ['Views from and beneath Gongchen Bridge', 'Evening lights in the Qiaoxi historic area', 'Canal walkways with passing boats'],
      ['拱宸橋の上と下からの眺め', '橋西歴史街区の夜灯り', '運河遊歩道と遊船を一緒に撮る視点'],
      ['궁천교 상·하부 시점', '차오시 역사거리의 야간 조명', '운하 산책로와 유람선을 함께 담는 포인트'],
    ),
    nearbyDining: list(
      ['桥西历史街区本地菜与茶馆', '运河边咖啡与轻食', '博物馆周边晚餐选择'],
      ['Local cuisine and tea houses in Qiaoxi', 'Canal-side cafes and light meals', 'Dinner options around the museums'],
      ['橋西歴史街区の郷土料理と茶館', '運河沿いのカフェと軽食', '博物館周辺の夕食スポット'],
      ['차오시 역사거리의 현지식과 찻집', '운하변 카페와 가벼운 식사', '박물관 주변 저녁 식사 선택지'],
    ),
    restrooms: text(
      '运河博物馆、桥西街区服务点与主要桥头附近较容易找到公厕，夜间仍以主街区节点最稳妥。',
      'Restrooms are easiest to find near canal museums, Qiaoxi service points and major bridgeheads; at night, stick to the main commercial nodes.',
      '運河博物館、橋西街区のサービス拠点、主要な橋のたもと付近で見つけやすいです。夜はメイン街区側を使うのが安心です。',
      '운하 박물관, 차오시 서비스 포인트, 주요 교량 입구 근처에서 찾기 쉽습니다. 밤에는 메인 상권 쪽을 이용하는 편이 안정적입니다.',
    ),
    storage: text(
      '街区型目的地更适合轻装，若有大件行李建议先放酒店或交通枢纽后再来。',
      'This neighbourhood-style destination works best with light bags; leave large luggage at your hotel or transport hub first.',
      '街区型スポットなので身軽な方が回りやすいです。大きな荷物はホテルや交通ターミナルに置いてから向かうのがおすすめです。',
      '거리형 목적지라 가볍게 움직이는 편이 좋습니다. 큰 짐은 호텔이나 교통 거점에 먼저 맡기고 오는 것이 낫습니다.',
    ),
    rainyPlan: text(
      '小雨可保留短距离桥区与博物馆组合；大雨时把重点转为中国京杭大运河博物馆和街区室内空间。',
      'In light rain, keep a short bridge district walk with museums; in heavier rain, shift the emphasis to the Grand Canal Museum and indoor street spaces.',
      '小雨なら橋周辺の短い散策と博物館の組み合わせがおすすめ。大雨なら運河博物館や屋内空間中心に切り替えてください。',
      '가벼운 비에는 다리 주변 짧은 산책과 박물관 조합이 좋고, 큰비에는 운하박물관과 실내 거리 공간 위주로 바꾸는 편이 좋습니다.',
    ),
    languageService: text(
      '核心博物馆和主要导视通常更容易看到双语信息，街巷型店铺仍以中文交流为主。',
      'The core museums and major signs are more likely to include bilingual information, while smaller lane-side shops still operate mostly in Chinese.',
      '主要博物館や大きな案内板では二言語情報を見つけやすい一方、小さな街路店は中国語中心です。',
      '핵심 박물관과 주요 표지판은 이중언어 정보가 있는 편이지만, 골목 상점은 중국어 중심인 경우가 많습니다.',
    ),
  },
  songcheng: {
    duration: text(
      '建议安排 4 至 6 小时；若要完整看主秀、街区演艺和夜景，基本按半天到晚间规划。',
      'Plan 4 to 6 hours; for the headline show, street performances and evening scenes, treat it as a half-day into night.',
      '4〜6時間が目安。メインショー、街区演目、夜景まで見るなら、半日から夜までで組むのが安心です。',
      '4~6시간이 적당하며, 메인 공연과 거리 공연, 야경까지 보면 반나절에서 저녁까지 잡는 편이 좋습니다.',
    ),
    bestArrival: text(
      '建议在主秀开场前 60 至 90 分钟到达，先完成检票、熟悉剧场与街区动线。',
      'Arrive 60 to 90 minutes before the headline show so you can clear entry and learn the theatre layout first.',
      'メインショー開演の60〜90分前到着がおすすめです。先に入場を済ませ、劇場と街区の動線を確認できます。',
      '메인 공연 시작 60~90분 전에 도착하는 편이 좋습니다. 먼저 입장하고 극장과 거리 동선을 익힐 수 있습니다.',
    ),
    peakAvoidance: text(
      '节假日晚间 17:30 至 19:30 的入园口、热门餐区和主剧场最拥挤，能提前到就不要压线。',
      'On holiday evenings, entry gates, popular food zones and the main theatre are busiest from 17:30 to 19:30; do not cut arrival too close.',
      '祝日の夕方17:30〜19:30は入園口、人気飲食エリア、メイン劇場が最も混みます。余裕を持って到着するのが安全です。',
      '공휴일 저녁 17:30~19:30에는 입장 게이트, 인기 식음 구역, 메인 극장이 가장 붐빕니다. 도착 시간을 촉박하게 잡지 않는 편이 좋습니다.',
    ),
    bestFor: list(
      ['第一次体验杭州大型演艺的人', '亲子、情侣与夜游人群', '想把表演和主题街区一次看完的游客'],
      ['First-time visitors wanting a headline performance experience', 'Families, couples and evening visitors', 'Travellers who want shows and themed streets in one stop'],
      ['杭州の大型ショーを初めて体験する人', '家族連れ、カップル、夜遊び目的の人', '公演とテーマ街区をまとめて楽しみたい人'],
      ['항저우 대형 공연을 처음 체험하는 사람', '가족, 커플, 야간 방문객', '공연과 테마 거리를 한 번에 보고 싶은 여행자'],
    ),
    photoSpots: list(
      ['主题街市主街透视', '夜场灯光与水面反射', '演艺开场前外立面'],
      ['Perspective views down the themed main street', 'Night lighting reflected on water', 'The theatre facade before showtime'],
      ['テーマ街のメインストリート遠近感', '夜の照明と水面反射', '開演前の劇場外観'],
      ['테마 거리 메인 스트리트 원근감', '야간 조명과 수면 반사', '공연 시작 전 극장 외관'],
    ),
    nearbyDining: list(
      ['园区内快餐与主题餐厅', '之江路沿线简餐', '演前演后补给型餐饮'],
      ['Fast food and themed restaurants inside the park', 'Casual dining along Zhijiang Road', 'Pre-show and post-show refuel options'],
      ['園内のファストフードとテーマレストラン', '之江路沿いの軽食', '開演前後に使いやすい補給系飲食'],
      ['공원 내부 패스트푸드와 테마 식당', '즈장로 일대 간단식', '공연 전후에 이용하기 좋은 식음'],
    ),
    restrooms: text(
      '剧场、主街入口与餐饮区通常分布较密，散场前后排队会明显增加，建议提前使用。',
      'Restrooms are usually clustered around theatres, main street entrances and dining zones; queues rise sharply before and after shows, so go early.',
      '劇場、メインストリート入口、飲食エリア周辺にまとまっています。開演前後と終演後は並びやすいので早めの利用がおすすめです。',
      '극장, 메인 스트리트 입구, 식음 구역 주변에 화장실이 모여 있습니다. 공연 전후와 종료 직후 대기가 늘어나므로 미리 이용하세요.',
    ),
    storage: text(
      '如携带外套、儿童用品或摄影包，建议入园后先询问服务台寄存安排，避免演出时携带过多随身物。',
      'If carrying coats, children’s items or camera bags, ask about storage at the service desk soon after entry to avoid taking too much into performances.',
      '上着、子ども用品、撮影バッグがある場合は、入園後すぐにサービスカウンターで預かりを確認しておくと演目観覧が楽です。',
      '겉옷, 아동용품, 카메라 가방이 있다면 입장 후 바로 서비스 데스크에서 보관 가능 여부를 묻는 편이 공연 관람에 편합니다.',
    ),
    rainyPlan: text(
      '雨天会削弱街区停留体验，但对主秀影响相对有限；建议把重心放在室内剧场和可避雨街段。',
      'Rain reduces the open-street experience but affects the headline indoor shows less; lean toward theatres and sheltered street segments.',
      '雨天は街区滞在の楽しさがやや落ちますが、メインショーへの影響は比較的限定的です。屋内劇場と屋根のある街路を中心にすると快適です。',
      '비가 오면 거리 체류 경험은 약해지지만 메인 실내 공연 영향은 상대적으로 적습니다. 실내 극장과 비를 피할 수 있는 구간 위주가 좋습니다.',
    ),
    languageService: text(
      '基础导视较易理解，但节目解说与互动仍以中文为主；国际游客更适合提前确认演出时间与座区。',
      'Basic wayfinding is manageable, but show commentary and interactions remain mostly in Chinese; international visitors benefit from checking schedules and seating in advance.',
      '基礎的な案内は比較的わかりやすい一方、演目解説や参加型要素は中国語中心です。事前に時間と座席位置を確認しておくと安心です。',
      '기본 안내는 비교적 이해하기 쉽지만, 공연 해설과 상호작용은 중국어 중심입니다. 시간표와 좌석 구역을 미리 확인하는 편이 좋습니다.',
    ),
  },
  'leifeng-pagoda': {
    duration: text(
      '建议安排 1.5 至 2.5 小时；若与净慈寺、南山路或西湖夜景联动，可延长到半天。',
      'Allow 1.5 to 2.5 hours, or longer if pairing it with Jingci Temple, Nanshan Road or a West Lake evening route.',
      '1.5〜2.5時間が目安。浄慈寺、南山路、西湖の夜景まで合わせるならもう少し長めに見ておくとよいです。',
      '1.5~2.5시간 정도가 적당하며, 징츠사나 난산로, 서호 야경과 묶으면 더 길게 잡는 편이 좋습니다.',
    ),
    bestArrival: text(
      '若以观景为主，建议上午开场后或日落前一小时到达，塔上视野最好。',
      'For the best views, arrive shortly after opening or in the hour before sunset.',
      '眺望重視なら開場直後か日没1時間前がおすすめです。塔上の景色が最もきれいに出ます。',
      '전망이 목적이라면 개장 직후나 일몰 1시간 전 도착이 좋습니다. 탑 위 시야가 가장 좋습니다.',
    ),
    peakAvoidance: text(
      '节假日 10:30 至 15:30 的电梯与高层观景面排队最明显，建议错开正午。',
      'During holidays, elevator lines and top viewing decks are busiest from 10:30 to 15:30; avoid the middle of the day.',
      '祝日は10:30〜15:30のエレベーター待ちと上層展望面が最も混みます。正午帯を外すのがおすすめです。',
      '공휴일에는 10:30~15:30 엘리베이터와 상층 전망 구역 대기가 가장 큽니다. 한낮은 피하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['想看经典西湖高点视角的游客', '情侣和摄影爱好者', '适合与南山路慢行组合的半日路线'],
      ['Visitors wanting a classic elevated West Lake view', 'Couples and photographers', 'Half-day itineraries paired with Nanshan Road'],
      ['西湖の定番高所ビューを見たい人', 'カップルや写真好き', '南山路散策と組み合わせる半日コース向き'],
      ['서호의 대표적인 고지대 전망을 보고 싶은 방문객', '커플과 사진 애호가', '난산로 산책과 묶는 반나절 코스'],
    ),
    photoSpots: list(
      ['塔上西湖全景', '塔前广场与倒影', '南山路边远望塔影'],
      ['Panoramic lake views from the tower', 'Reflections from the forecourt', 'Tower silhouette from Nanshan Road'],
      ['塔上からの西湖全景', '塔前広場の反射', '南山路から望む塔影'],
      ['탑 위 서호 전경', '탑 앞 광장 반사', '난산로에서 멀리 보는 탑 실루엣'],
    ),
    nearbyDining: list(
      ['南山路餐厅与咖啡', '净慈寺周边简餐', '湖滨方向晚餐延伸选择'],
      ['Restaurants and cafes on Nanshan Road', 'Casual dining near Jingci Temple', 'Dinner options extending toward Hubin'],
      ['南山路のレストランとカフェ', '浄慈寺周辺の軽食', '湖浜方面へ延ばせる夕食選択肢'],
      ['난산로 레스토랑과 카페', '징츠사 주변 간단식', '후빈 방향으로 이어지는 저녁 선택지'],
    ),
    restrooms: text(
      '入口检票区、塔基服务点和主要观景层附近通常能找到洗手间，排队高峰时建议提前使用。',
      'Restrooms are typically available near entry checkpoints, the tower base service point and major viewing levels; go before queues build.',
      '入口のチケット動線、塔基部のサービス拠点、主要な展望階付近にあることが多いです。混む前の利用がおすすめです。',
      '입장 검표 구역, 탑 기단 서비스 포인트, 주요 전망층 주변에 보통 화장실이 있습니다. 붐비기 전에 미리 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '高层观景更适合轻装，若有大件物品建议先在周边酒店或交通点处理，不要把行李带上观景层。',
      'Upper-level viewing is easier with light bags; leave large items at hotels or transport points rather than taking them up the tower.',
      '上層展望は身軽な方が快適です。大きな荷物はホテルや交通拠点で預け、展望階へ持ち込まない方が無難です。',
      '상층 전망은 가볍게 올라가는 편이 좋습니다. 큰 짐은 호텔이나 교통 거점에 두고 전망층으로 가져가지 않는 편이 좋습니다.',
    ),
    rainyPlan: text(
      '小雨会压低远景能见度，但塔内观景和传说展示仍可保留；若大雨或雷暴，建议改为南山路室内场馆。',
      'Light rain lowers visibility but the tower interior and legend displays still work; in heavy rain or storms, switch to indoor venues along Nanshan Road.',
      '小雨では遠景が弱まりますが、塔内の見学や伝説展示は保てます。大雨や雷の際は南山路沿いの屋内施設へ切り替えるのが安全です。',
      '가벼운 비에는 원경 시야가 떨어지지만 탑 내부와 전설 전시는 볼 수 있습니다. 큰비나 뇌우에는 난산로 실내 시설로 전환하는 편이 안전합니다.',
    ),
    languageService: text(
      '基础导视对国际游客相对友好，但与白蛇传相关的文化解读更适合搭配英文说明资料。',
      'Basic wayfinding is relatively international-friendly, but the White Snake legend context is easier with supplemental English notes.',
      '基本案内は比較的わかりやすいですが、白蛇伝に関わる文化的背景は英語資料があると理解しやすいです。',
      '기본 안내는 비교적 친절하지만, 백사전설 관련 문화 맥락은 영어 설명 자료가 있으면 더 이해하기 쉽습니다.',
    ),
  },
  'hangzhou-botanical-garden': {
    duration: text(
      '建议安排 2 至 3 小时；花季与慢拍人群可延长到半天。',
      'Set aside 2 to 3 hours, or half a day in flowering seasons or for slower photography walks.',
      '2〜3時間が目安。花の季節や写真をゆっくり撮るなら半日でも楽しめます。',
      '2~3시간 정도가 적당하며, 꽃철이나 사진 위주라면 반나절도 좋습니다.',
    ),
    bestArrival: text(
      '建议上午 8:30 至 10:30 入园，气温更舒适，园路也最安静。',
      'Aim to enter between 8:30 and 10:30 when temperatures are gentler and the garden paths are quietest.',
      '8:30〜10:30 の入園がおすすめです。気温が穏やかで、園路も最も静かです。',
      '오전 8:30~10:30 입장이 좋습니다. 기온이 더 쾌적하고 동선도 가장 조용합니다.',
    ),
    peakAvoidance: text(
      '春季花期和周末午后的人流最集中，建议错开热门温室、花径与入口广场。',
      'Spring bloom periods and weekend afternoons are the busiest; time-shift the most popular greenhouses, floral walks and entrance plazas.',
      '春の花期と週末午後が最も混みます。人気の温室、花の小径、入口広場は時間をずらすと快適です。',
      '봄 개화기와 주말 오후가 가장 붐빕니다. 인기 온실과 꽃길, 입구 광장은 시간을 비껴 가는 편이 좋습니다.',
    ),
    bestFor: list(
      ['植物、园林与安静步行爱好者', '家庭轻松散步', '春秋季节摄影'],
      ['Plant lovers and quiet walkers', 'Easy family outings', 'Spring and autumn photography'],
      ['植物や庭園、静かな散策が好きな人', '家族で気軽に歩きたい人', '春秋の写真撮影'],
      ['식물과 정원, 조용한 산책을 좋아하는 사람', '가벼운 가족 산책', '봄·가을 사진 촬영'],
    ),
    photoSpots: list(
      ['花径与林下步道', '季节花卉集中区', '山脚转角与园路层次'],
      ['Flower paths and shaded walks', 'Seasonal bloom clusters', 'Foothill turns and layered garden paths'],
      ['花の小径と木陰の遊歩道', '季節花卉のまとまるエリア', '山裾の曲がり角と園路の重なり'],
      ['꽃길과 숲 그늘 산책로', '계절 꽃 집중 구역', '산기슭 모퉁이와 겹치는 정원 길'],
    ),
    nearbyDining: list(
      ['园区入口简餐与茶饮', '玉泉周边餐饮', '灵隐与西湖西线延伸餐厅'],
      ['Light meals near the entrance', 'Dining around Yuquan', 'Extended options toward Lingyin and the western lake route'],
      ['入口付近の軽食とティー', '玉泉周辺の飲食', '霊隠や西湖西側へ延ばせる食事処'],
      ['입구 주변 간단식과 차', '위취안 주변 식당', '링인·서호 서측으로 이어지는 식당'],
    ),
    restrooms: text(
      '入口、主要园路节点和热门花区周边通常可找到公厕，远离主线前建议先使用。',
      'Restrooms are usually available near the entrance, key path nodes and popular flower zones; use them before heading into quieter sections.',
      '入口、主要な園路の結節点、人気花区周辺で見つけやすいです。奥へ入る前に利用しておくと安心です。',
      '입구, 주요 산책로 결절점, 인기 꽃 구역 주변에서 찾기 쉽습니다. 한적한 구간으로 들어가기 전 미리 이용하세요.',
    ),
    storage: text(
      '植物园更适合轻装慢走，若带摄影设备可准备轻便防雨包，大件行李不建议带入长线路线。',
      'The garden works best with light bags; if you are carrying camera gear, use a compact rainproof bag and avoid bringing large luggage onto longer loops.',
      '植物園は身軽に歩く方が快適です。撮影機材がある場合は小型の防雨バッグ程度が向いており、大きな荷物は長い周遊には不向きです。',
      '식물원은 가볍게 걷는 편이 좋습니다. 촬영 장비가 있다면 작은 방수 가방 정도가 적당하며 큰 짐은 긴 동선에 맞지 않습니다.',
    ),
    rainyPlan: text(
      '小雨时林下步道别有气氛，但花季泥地与坡路会更滑；大雨建议缩短外圈，改为入口周边与近距离观花。',
      'Light rain can be atmospheric under the trees, but muddy flower routes and slopes become slick; in heavier rain, keep to the entrance zones and shorter bloom walks.',
      '小雨は林間歩道に雰囲気がありますが、花期の土道や坂は滑りやすくなります。強い雨なら入口周辺の短い観花ルート中心がおすすめです。',
      '가벼운 비는 숲길 분위기를 살리지만 꽃철 흙길과 경사 구간은 미끄럽습니다. 큰비에는 입구 주변의 짧은 꽃길 위주가 낫습니다.',
    ),
    languageService: text(
      '基础植物分区和主要导视通常能理解，但具体植物解释仍以中文为主，适合搭配图像识别或英文植物清单。',
      'Major zones and core signs are usually understandable, though detailed plant interpretation remains mostly Chinese; image recognition tools or an English plant list help.',
      '主要な区画と大きな案内は把握しやすいですが、細かな植物解説は中国語中心です。画像検索や英語の植物リストを併用すると便利です。',
      '주요 구역과 큰 표지판은 비교적 이해하기 쉽지만, 세부 식물 설명은 중국어 중심입니다. 식물 식별 앱이나 영어 목록을 함께 쓰면 좋습니다.',
    ),
  },
  'hangzhou-zoo': {
    duration: text(
      '建议安排 2.5 至 4 小时；若有儿童或想完整看喂食时段，建议半天。',
      'Allow 2.5 to 4 hours, or half a day with children or if timing your visit around feeding periods.',
      '2.5〜4時間が目安。子ども連れや給餌時間も見たい場合は半日あると安心です。',
      '2.5~4시간 정도가 적당하며, 아이와 함께이거나 먹이 주는 시간까지 보려면 반나절이 좋습니다.',
    ),
    bestArrival: text(
      '建议上午到达，动物活跃度和体感都更好，也更适合避开午后晒和人流。',
      'Morning visits usually bring more active animals, easier temperatures and lighter traffic.',
      '午前到着がおすすめです。動物が比較的活発で、気温も人流も楽です。',
      '오전 방문이 좋습니다. 동물 활동성이 더 좋고, 기온과 인파도 한결 편합니다.',
    ),
    peakAvoidance: text(
      '周末和假日下午的热门馆舍会出现亲子人流集中，建议先走高热度馆舍再慢慢下行。',
      'On weekend and holiday afternoons, the most popular houses fill with family groups; start with those first before slowing into the rest of the route.',
      '週末や祝日の午後は人気館舎に家族連れが集中します。先に人気館舎を回り、その後ゆっくり下る流れがおすすめです。',
      '주말·공휴일 오후에는 인기 전시관에 가족 단위 인파가 몰립니다. 먼저 인기 구역부터 보고 나머지를 천천히 도는 편이 좋습니다.',
    ),
    bestFor: list(
      ['亲子家庭', '喜欢自然教育内容的游客', '想安排轻松半日路线的人'],
      ['Families with children', 'Visitors interested in nature education', 'Travellers planning an easy half-day'],
      ['子ども連れの家族', '自然教育に関心のある人', '気軽な半日コースを組みたい人'],
      ['아이 동반 가족', '자연 교육 콘텐츠에 관심 있는 방문객', '가벼운 반나절 코스를 원하는 사람'],
    ),
    photoSpots: list(
      ['山林背景下的户外活动场', '高点俯看园路与树冠', '亲子休憩区的轻松记录'],
      ['Outdoor enclosures with wooded backdrops', 'Higher points looking across paths and tree canopy', 'Relaxed family moments in rest areas'],
      ['山林を背景にした屋外展示', '高所から見下ろす園路と樹冠', '休憩エリアでの家族の記録'],
      ['숲 배경의 야외 전시장', '높은 지점에서 내려다보는 동선과 수관', '휴게 구역의 가족 기록 사진'],
    ),
    nearbyDining: list(
      ['园内简餐和补给点', '虎跑路沿线餐饮', '动物园与西湖南线联动用餐'],
      ['Simple meals and refreshment points inside', 'Dining along Hupao Road', 'Meals linked with the southern West Lake route'],
      ['園内の軽食と補給スポット', '虎跑路沿いの飲食', '西湖南線と組み合わせる食事'],
      ['원내 간단식과 보급 포인트', '후파오로 일대 식당', '서호 남선과 묶는 식사'],
    ),
    restrooms: text(
      '入口、热门馆舍与亲子休息区通常配置较稳，带孩子出行建议每到大节点就顺手处理。',
      'Restrooms are usually reliable near the entrance, popular houses and family rest zones; with children, use them at each major node.',
      '入口、人気館舎、家族向け休憩エリア付近は比較的安定しています。子ども連れなら大きな区切りごとに使っておくと安心です。',
      '입구, 인기 전시관, 가족 휴게 구역 주변은 비교적 안정적으로 화장실이 있습니다. 아이와 함께라면 큰 구간마다 미리 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '婴儿车、小零食和备用衣物更实用；若有大件行李，建议先在酒店或交通点处理后再入园。',
      'Strollers, snacks and spare clothes are useful; large luggage should be left at hotels or transport points before entering.',
      'ベビーカー、軽食、着替えは便利ですが、大きな荷物はホテルや交通拠点で預けてから入園するのがおすすめです。',
      '유모차, 간식, 여벌옷이 실용적이며, 큰 짐은 호텔이나 교통 거점에 먼저 맡기고 입장하는 편이 좋습니다.',
    ),
    rainyPlan: text(
      '雨天时户外活动区体验下降明显，可优先看室内馆舍并缩短全园步行。',
      'Rain affects outdoor enclosures noticeably; prioritise indoor houses and shorten the overall route.',
      '雨天は屋外展示の見やすさが落ちます。屋内館舎を優先し、全体の歩行距離を短めにするのが無難です。',
      '비 오는 날에는 야외 구역 체험이 많이 떨어집니다. 실내 전시관을 우선하고 전체 도보 거리를 줄이는 편이 좋습니다.',
    ),
    languageService: text(
      '动物名称标识相对直观，但更深入的讲解常以中文为主，国际家庭可提前准备基本动物词汇或翻译工具。',
      'Animal labels are often straightforward, though deeper interpretation tends to be Chinese-first; international families may want simple vocabulary support or translation tools.',
      '動物名表示は比較的わかりやすいですが、詳しい解説は中国語中心です。国際家族は簡単な翻訳ツールがあると便利です。',
      '동물 이름 표시는 비교적 직관적이지만, 깊은 설명은 중국어 중심입니다. 해외 가족이라면 간단한 번역 도구를 준비하면 좋습니다.',
    ),
  },
  'hu-xueyan-residence': {
    duration: text(
      '建议安排 1 至 1.5 小时；若同时串联河坊街、南宋御街，可做 2 至 3 小时街区线。',
      'Set aside 1 to 1.5 hours, or 2 to 3 hours if linking it with Hefang Street and Southern Song Imperial Street.',
      '1〜1.5時間が目安。河坊街や南宋御街とつなげるなら、街区全体で2〜3時間見ておくとよいです。',
      '1~1.5시간 정도가 적당하며, 허팡제와 남송어가까지 묶으면 2~3시간 거리 코스로 좋습니다.',
    ),
    bestArrival: text(
      '建议工作日上午或开馆后尽早进入，庭院细节与室内观感更安静。',
      'Weekday mornings or early entry after opening are best for a quieter look at the courtyards and interiors.',
      '平日の午前や開館直後がおすすめです。中庭の細部や室内を静かに見やすくなります。',
      '평일 오전이나 개관 직후 입장이 좋습니다. 마당 디테일과 실내를 더 조용히 볼 수 있습니다.',
    ),
    peakAvoidance: text(
      '节假日午后团队客较多，狭窄廊道与房间会显得拥挤，建议先看室内主轴再回庭院。',
      'On holiday afternoons, group tours make the narrower corridors and rooms feel crowded; see the main interiors first, then return to the courtyards.',
      '祝日の午後は団体客が増え、細い回廊や部屋が混みやすくなります。まず室内主軸を見て、その後庭園へ戻る流れが回りやすいです。',
      '공휴일 오후에는 단체 방문이 늘어 좁은 복도와 방이 혼잡해집니다. 먼저 실내 메인 축선을 보고 나중에 마당으로 돌아가는 편이 좋습니다.',
    ),
    bestFor: list(
      ['历史建筑与晚清生活史爱好者', '喜欢木作、园林细节的人', '雨天也想保留文化内容的游客'],
      ['Visitors interested in historic houses and late Qing life', 'People who enjoy woodwork and garden detail', 'Travellers wanting a cultural stop even in rain'],
      ['歴史建築や清末の生活史に関心のある人', '木工や庭園の細部が好きな人', '雨天でも文化枠を残したい人'],
      ['역사 건축과 청말 생활사에 관심 있는 사람', '목조 디테일과 정원 세부를 좋아하는 사람', '비 와도 문화 코스를 유지하고 싶은 여행자'],
    ),
    photoSpots: list(
      ['门厅与庭院轴线', '木雕窗格与天井光线', '水院与回廊交接处'],
      ['The entrance hall and courtyard axis', 'Carved windows in skylight', 'The junction of water court and corridor'],
      ['門庁と中庭の軸線', '木彫窓格子と天窓の光', '水庭と回廊のつながり'],
      ['현관 홀과 마당 축선', '목조 창살과 천창 빛', '수정원과 회랑이 만나는 지점'],
    ),
    nearbyDining: list(
      ['河坊街与南宋御街杭帮小吃', '清河坊传统点心', '上城老城厢本地馆子'],
      ['Hangzhou snacks on Hefang Street and Imperial Street', 'Traditional pastries in Qinghefang', 'Local restaurants in Shangcheng old town'],
      ['河坊街や御街の杭州軽食', '清河坊の伝統菓子', '上城旧市街のローカル食堂'],
      ['허팡제와 어가의 항저우 간식', '칭허팡 전통 디저트', '상청 구시가지 현지 식당'],
    ),
    restrooms: text(
      '故居入口与参观主线节点通常可找到洗手间，老宅空间较紧凑，建议进入前先确认位置。',
      'Restrooms are usually available near the entrance and along the main route; because the residence is compact, note their location before you start.',
      '入口や見学主線の節点で見つけやすいです。旧邸は空間がややコンパクトなので、入場前に位置を把握しておくと安心です。',
      '입구와 관람 메인 동선 결절점 부근에서 찾을 수 있습니다. 고택 공간이 촘촘하므로 입장 전 위치를 확인해 두는 편이 좋습니다.',
    ),
    storage: text(
      '老宅动线不适合大件行李，建议轻装进入；摄影设备请注意狭窄室内转身空间。',
      'Large luggage does not fit the old-house circulation well; enter light and mind tight indoor turning space with camera gear.',
      '大きな荷物は旧邸の動線に向きません。身軽に入り、撮影機材がある場合は狭い室内での取り回しに注意してください。',
      '큰 짐은 고택 동선과 잘 맞지 않습니다. 가볍게 들어가고, 촬영 장비가 있다면 좁은 실내 회전 공간에 주의하세요.',
    ),
    rainyPlan: text(
      '这是很适合雨天保留的文化点位，小雨和中雨均可正常参观，强降雨时只需预留室外换鞋与防滑时间。',
      'This is a strong rainy-day cultural stop; light or moderate rain still works well, with only extra time needed for wet entrances and slippery thresholds.',
      '雨の日に組み込みやすい文化スポットです。小雨や中雨でも見学しやすく、強い雨では入口まわりの濡れと滑りにだけ注意してください。',
      '비 오는 날에도 유지하기 좋은 문화 코스입니다. 약한 비나 보통 비에는 무리 없고, 큰비에는 입구와 미끄러운 문턱만 주의하면 됩니다.',
    ),
    languageService: text(
      '建筑空间直观，但家族史与商业史解读更适合配合英文图文资料阅读。',
      'The architecture reads visually, but the family and business history lands better with supplemental English reading.',
      '建築空間そのものは見てわかりやすいですが、一族史や商業史は英語資料があると理解しやすいです。',
      '건축 공간은 직관적이지만, 가문사와 상업사 해설은 영어 자료가 있으면 더 이해하기 쉽습니다.',
    ),
  },
  liuhetower: {
    duration: text(
      '建议安排 1.5 至 2.5 小时；若叠加钱塘江观潮或江岸慢行，可延长到半天。',
      'Allow 1.5 to 2.5 hours, or half a day if adding a Qiantang River walk or tide viewing.',
      '1.5〜2.5時間が目安。銭塘江の散策や潮見を重ねるなら半日でもちょうどよいです。',
      '1.5~2.5시간이 적당하며, 첸탕강 산책이나 조수 관람을 더하면 반나절도 좋습니다.',
    ),
    bestArrival: text(
      '建议下午到达，江景光线更开阔；若遇观潮季节，请围绕官方潮时提前到场。',
      'Afternoons give broader river light; in tide-viewing season, arrive around the official tide timetable.',
      '午後の到着で江景の光が開けます。潮見シーズンは公式の潮時刻に合わせて早めに着くのがおすすめです。',
      '오후 도착이 강 풍경 빛이 좋고, 조수 관람 시즌에는 공식 조시표 기준으로 미리 도착하는 편이 좋습니다.',
    ),
    peakAvoidance: text(
      '节假日和观潮窗口前后的人流增长很快，若不是专门追潮，尽量避开相关时段。',
      'Crowds build quickly around holidays and tide-viewing windows; if you are not specifically here for the tide, avoid those time bands.',
      '祝日や潮見の前後は人の増え方が速いです。潮目的でなければ、その時間帯を外す方が快適です。',
      '공휴일과 조수 관람 시간 전후에는 인파가 빠르게 늘어납니다. 특별히 조수를 보려는 것이 아니라면 그 시간대는 피하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['喜欢登高与江景的人', '想感受钱塘江地标气质的游客', '可与之江路线串联的半日安排'],
      ['Visitors who enjoy elevated river views', 'Travellers seeking a signature Qiantang River landmark', 'Half-day trips along the Zhijiang route'],
      ['高所や江景が好きな人', '銭塘江らしいランドマークを感じたい人', '之江路ルートと組み合わせる半日向き'],
      ['높은 전망과 강 풍경을 좋아하는 사람', '첸탕강 랜드마크 감성을 느끼고 싶은 방문객', '즈장로 루트와 묶는 반나절 일정'],
    ),
    photoSpots: list(
      ['塔前江岸开阔面', '塔体仰拍与层檐', '高点远望钱塘江桥线'],
      ['Open riverfront in front of the tower', 'Low-angle views of the eaves', 'Higher lookouts over the bridge line'],
      ['塔前の開けた江岸', '塔体を見上げる構図', '高所から望む銭塘江の橋景'],
      ['탑 앞 넓은 강변', '처마를 올려다보는 구도', '높은 곳에서 보는 첸탕강 교량선'],
    ),
    nearbyDining: list(
      ['之江路沿线简餐与江景餐厅', '观潮后补给型餐饮', '与宋城、西湖西线联动用餐'],
      ['Casual and river-view dining along Zhijiang Road', 'Refuel spots after tide watching', 'Meals linked with Songcheng or the western lake route'],
      ['之江路沿いの軽食と江景レストラン', '潮見後の補給向け飲食', '宋城や西湖西側と組み合わせる食事'],
      ['즈장로 일대 간단식과 강변 식당', '조수 관람 후 보급형 식당', '송성·서호 서측과 묶는 식사'],
    ),
    restrooms: text(
      '入口、塔基服务点和江岸主要节点通常可找到洗手间，观潮时段请尽量提前使用。',
      'Restrooms are usually near the entrance, tower base and main riverfront nodes; during tide periods, use them before crowds thicken.',
      '入口、塔基部のサービス拠点、江岸の主要結節点にあることが多いです。潮見の時間帯は混む前の利用がおすすめです。',
      '입구, 탑 기단 서비스 포인트, 강변 주요 결절점에 대체로 있습니다. 조수 관람 시간에는 붐비기 전에 이용하세요.',
    ),
    storage: text(
      '江岸风大又有台阶，建议轻装登塔；大件行李不适合在观景与爬塔动线中携带。',
      'The riverfront can be windy and stair-heavy, so light bags are best; large luggage does not suit the viewing and tower-climb route.',
      '江岸は風が強く階段もあるため、身軽な方が快適です。大きな荷物は展望や登塔動線に向きません。',
      '강변은 바람이 강하고 계단이 있어 가볍게 움직이는 편이 좋습니다. 큰 짐은 전망·등탑 동선에 적합하지 않습니다.',
    ),
    rainyPlan: text(
      '雨天会明显削弱江景能见度，若不是专程看塔，可考虑改为室内文化馆或把江岸停留压缩到最短。',
      'Rain reduces river visibility substantially; unless the tower itself is the point, consider indoor cultural venues or a much shorter river stay.',
      '雨天は江景の見え方がかなり弱まります。塔が主目的でなければ、屋内文化施設へ切り替えるか江岸滞在を短くするのが無難です。',
      '비 오는 날에는 강 풍경 시야가 크게 떨어집니다. 탑 자체가 목적이 아니라면 실내 문화시설로 바꾸거나 강변 체류를 짧게 줄이는 편이 좋습니다.',
    ),
    languageService: text(
      '地标空间本身容易理解，但关于钱塘潮与塔史的深入解说更适合配合翻译资料。',
      'The landmark reads clearly on its own, but deeper context on the Qiantang tide and tower history benefits from translated material.',
      'ランドマーク自体は直感的ですが、銭塘潮や塔の歴史を深く知るには翻訳資料があると理解しやすいです。',
      '랜드마크 자체는 직관적이지만, 첸탕강 조수와 탑 역사에 대한 깊은 해설은 번역 자료가 있으면 더 좋습니다.',
    ),
  },
  guozhuang: {
    duration: text(
      '建议安排 45 至 90 分钟；若联动杨公堤、曲院风荷或西湖西线，适合作为精致短停。',
      'Allow 45 to 90 minutes; paired with Yang Causeway or the western lake route, it works best as a refined short stop.',
      '45〜90分が目安。楊公堤や西湖西側ルートと合わせると、上質な短い立ち寄りになります。',
      '45~90분 정도가 적당하며, 양공제나 서호 서측 루트와 함께하면 정교한 짧은 정차 코스로 좋습니다.',
    ),
    bestArrival: text(
      '建议上午开园后或下午 16:00 前后到达，园林层次和光线最柔和。',
      'Arrive after opening or around 16:00 for the softest garden light and layered views.',
      '開園後まもなくか16時前後の到着がおすすめです。庭園の階層感と光が最もやわらかく出ます。',
      '개장 직후나 오후 16시 전후 도착이 좋습니다. 정원 레이어와 빛이 가장 부드럽습니다.',
    ),
    peakAvoidance: text(
      '花季和周末午后的小尺度园路最容易拥挤，建议避开正午，快速进出不要久堵门口。',
      'During flower seasons and weekend afternoons, the compact paths crowd easily; avoid midday and keep entrance lingering brief.',
      '花の季節や週末午後はコンパクトな園路が混みやすいです。正午帯を避け、入口周辺で長く滞留しないのが快適です。',
      '꽃철과 주말 오후에는 작은 정원 길이 쉽게 붐빕니다. 한낮을 피하고 입구에 오래 머물지 않는 편이 좋습니다.',
    ),
    bestFor: list(
      ['喜欢江南园林细部的人', '摄影与安静散步人群', '不想走太远但想看精致空间的游客'],
      ['Visitors who enjoy Jiangnan garden detail', 'Photographers and quiet walkers', 'Travellers wanting a compact but refined stop'],
      ['江南庭園の細部が好きな人', '写真や静かな散策を楽しむ人', '長く歩かずに美しい空間を見たい人'],
      ['강남 정원 디테일을 좋아하는 사람', '사진과 조용한 산책을 즐기는 방문객', '멀리 걷지 않고도 정교한 공간을 보고 싶은 사람'],
    ),
    photoSpots: list(
      ['临湖亭台与借景', '窗洞取景框', '花木与曲桥小景'],
      ['Pavilions borrowing lake views', 'Window openings used as frames', 'Flowers and small curved bridges'],
      ['湖を借景にする亭台', '窓枠を使った構図', '花木と小さな曲橋'],
      ['호수를 빌려오는 정자', '창문 틀을 이용한 프레이밍', '꽃나무와 작은 곡교'],
    ),
    nearbyDining: list(
      ['杨公堤与西湖西线茶饮', '曲院风荷周边简餐', '湖西安静系咖啡馆'],
      ['Tea stops along Yang Causeway and the western lake', 'Casual meals near Quyuan Fenghe', 'Quieter west-lake cafes'],
      ['楊公堤や西湖西側のティー', '曲院風荷周辺の軽食', '静かな湖西カフェ'],
      ['양공제와 서호 서측 차 공간', '취위안펑허 주변 간단식', '서호 서측의 조용한 카페'],
    ),
    restrooms: text(
      '小园林内部厕所点位有限，入园前后可优先在入口服务点或周边公园节点处理。',
      'Restroom points inside the compact garden are limited; use the entrance service area or nearby park nodes before or after your visit.',
      '小規模庭園の内部トイレは限られます。入園前後に入口サービス拠点や周辺公園のトイレを使うと安心です。',
      '소규모 정원 내부 화장실은 제한적일 수 있습니다. 입장 전후 입구 서비스 포인트나 주변 공원 지점에서 먼저 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '郭庄更适合轻装拍照和慢走，大件行李不适合在园林小尺度空间里携带。',
      'Guo Villa is best experienced with light bags; large luggage does not suit the compact garden spaces.',
      '郭荘は身軽に写真を撮りながら歩くのに向いています。大きな荷物は庭園の小さな空間に合いません。',
      '궈좡은 가볍게 사진 찍으며 걷기에 적합합니다. 큰 짐은 작은 정원 공간과 잘 맞지 않습니다.',
    ),
    rainyPlan: text(
      '细雨时园林气氛很好，但青石与木面会更滑；大雨则建议把这里缩短成短停，不要安排长时间发呆停留。',
      'Drizzle suits the garden atmosphere, but stone and timber surfaces become slick; in heavier rain, keep this as a short stop rather than a long linger.',
      '小雨は庭園の雰囲気に合いますが、石や木の床は滑りやすくなります。強い雨なら短い立ち寄りにとどめるのが無難です。',
      '잔비는 정원 분위기에 잘 맞지만 돌과 목재 면이 미끄럽습니다. 큰비에는 오래 머무르기보다 짧게 보고 나오는 편이 좋습니다.',
    ),
    languageService: text(
      '空间美感直观，但园林借景与历史背景的理解更适合提前看一段英文简介。',
      'The beauty reads immediately, but understanding borrowed scenery and historical context benefits from a short English introduction beforehand.',
      '空間の美しさ自体は直感的ですが、借景や歴史背景は短い英語説明を先に読んでおくと理解しやすいです。',
      '공간의 미감은 직관적이지만, 차경과 역사 배경은 짧은 영어 소개를 미리 보면 더 이해하기 쉽습니다.',
    ),
  },
  'xiaohe-street': {
    duration: text(
      '建议安排 1.5 至 3 小时；适合和桥西运河线一起做一段慢速街区步行。',
      'Allow 1.5 to 3 hours, especially if pairing it with the Qiaoxi canal route as a slower neighbourhood walk.',
      '1.5〜3時間が目安です。橋西の運河ルートと合わせると、ゆっくりした街区散策になります。',
      '1.5~3시간 정도가 적당하며, 차오시 운하 루트와 묶으면 느린 거리 산책 코스로 좋습니다.',
    ),
    bestArrival: text(
      '下午晚些时候到达最舒服，可以一路走到傍晚亮灯时段。',
      'Late afternoon is the most comfortable arrival window, carrying you naturally into the evening lights.',
      'やや遅めの午後到着が最も心地よく、そのまま夕方の灯りまでつなげやすいです。',
      '늦은 오후 도착이 가장 편하고, 그대로 저녁 조명 시간까지 이어가기 좋습니다.',
    ),
    peakAvoidance: text(
      '周末晚饭前后的小桥和主街最拥挤，建议向支巷和水边支线分流。',
      'The small bridges and main street are busiest around weekend dinner hours; peel off into side lanes and waterside spurs.',
      '週末の夕食前後は小橋とメインストリートに人が集まります。脇道や水辺の支線に入ると歩きやすいです。',
      '주말 저녁 식사 전후에는 작은 다리와 메인 거리로 인파가 몰립니다. 옆 골목과 수변 지선으로 분산하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['喜欢老街日常感的人', '咖啡、小店和慢逛人群', '不追打卡而追气氛的游客'],
      ['Visitors who enjoy lived-in historic streets', 'Cafe and small-shop wanderers', 'Travellers chasing atmosphere more than landmark checklists'],
      ['生活感のある旧街路が好きな人', 'カフェや小店をのんびり巡りたい人', '有名打卡より雰囲気を重視する人'],
      ['생활감 있는 옛 거리를 좋아하는 사람', '카페와 작은 가게를 천천히 도는 방문객', '체크리스트보다 분위기를 중시하는 여행자'],
    ),
    photoSpots: list(
      ['小桥与窄巷交汇处', '白墙木窗临水面', '傍晚亮灯后的河岸'],
      ['Junctions of small bridges and narrow lanes', 'White walls and timber windows over water', 'Riverbanks after the evening lights come on'],
      ['小橋と細路地の交差点', '白壁と木窓の水辺', '夕方の点灯後の岸辺'],
      ['작은 다리와 좁은 골목이 만나는 곳', '흰 벽과 목재 창의 수변', '불이 켜진 뒤의 강변'],
    ),
    nearbyDining: list(
      ['小河直街咖啡与创意简餐', '运河边本地小馆', '桥西方向可延伸的晚餐选择'],
      ['Cafes and creative casual dining on Xiaohe Street', 'Local eateries by the canal', 'Dinner options continuing toward Qiaoxi'],
      ['小河直街のカフェと軽食', '運河沿いのローカル食堂', '橋西方面へ延ばせる夕食選択肢'],
      ['샤오허 거리 카페와 가벼운 식사', '운하변 현지 식당', '차오시 방향으로 이어지는 저녁 식사'],
    ),
    restrooms: text(
      '街区厕所通常依赖游客服务点、商圈节点或合作商户，晚间请优先在主街区解决。',
      'Restrooms in the district usually depend on service points, retail nodes or partner venues; at night, handle this on the main street first.',
      '街区のトイレは案内所、商業拠点、提携店舗に依ることが多いです。夜はまずメイン街区で済ませる方が安心です。',
      '거리 화장실은 안내소, 상업 거점, 협력 매장에 의존하는 편입니다. 밤에는 메인 거리 쪽에서 먼저 해결하는 편이 좋습니다.',
    ),
    storage: text(
      '老街空间窄、步行感强，不建议拖箱进入；更适合作为饭前饭后的轻装散步。',
      'The old street is narrow and walk-oriented, so wheeled luggage is a poor fit; it works better as a light-bag pre- or post-meal stroll.',
      '旧街路は狭く歩行中心なので、スーツケースを引いて入るのには向きません。食前食後の身軽な散歩にちょうどよいです。',
      '옛 거리는 좁고 보행 중심이라 캐리어를 끌고 들어가기엔 맞지 않습니다. 식사 전후 가볍게 걷기에 더 적합합니다.',
    ),
    rainyPlan: text(
      '小雨可以保留街景氛围，但持续降雨会显著压缩停留舒适度，建议转去博物馆或桥西室内空间。',
      'Light rain can preserve the mood, but sustained rain sharply reduces comfort; in that case, switch to museums or indoor Qiaoxi spaces.',
      '小雨なら街景の雰囲気は残せますが、雨が続くと滞在の快適さは大きく下がります。博物館や橋西の屋内空間へ切り替えるのがおすすめです。',
      '가벼운 비는 거리 분위기를 살릴 수 있지만, 계속 비가 오면 체류 쾌적함이 크게 떨어집니다. 박물관이나 차오시 실내 공간으로 바꾸는 편이 좋습니다.',
    ),
    languageService: text(
      '街区气质友好，但小店沟通以中文为主，国际游客更适合提前收藏想去的店与地图定位。',
      'The district feels welcoming, but smaller shops work mainly in Chinese; international visitors benefit from saving favourite spots and map pins in advance.',
      '街区の雰囲気は親しみやすいですが、小さな店は中国語中心です。行きたい店や地図ピンを事前保存しておくと安心です。',
      '거리 분위기는 친근하지만 작은 가게는 중국어 중심입니다. 가고 싶은 가게와 지도 핀을 미리 저장해 두면 좋습니다.',
    ),
  },
  'southern-song-imperial-street': {
    duration: text(
      '建议安排 1.5 至 3 小时；若与河坊街、胡雪岩故居联动，可顺成半天老城步行。',
      'Allow 1.5 to 3 hours, or a half-day old-city walk if linking it with Hefang Street and Hu Xueyan Residence.',
      '1.5〜3時間が目安。河坊街や胡雪岩故居と合わせると、旧市街半日散策としてまとまります。',
      '1.5~3시간 정도가 적당하며, 허팡제와 후쉐옌 고거를 함께 보면 구시가지 반나절 산책 코스가 됩니다.',
    ),
    bestArrival: text(
      '若重视街景和用餐，17:00 后到达最合适；若想安静看街巷层次，工作日上午更舒服。',
      'Arrive after 17:00 for street life and dining, or on weekday mornings for a quieter read of the neighbourhood fabric.',
      '街並みと食事を重視するなら17時以降、静かに街路の層を見たいなら平日午前がおすすめです。',
      '거리 풍경과 식사가 목적이면 17시 이후, 조용히 골목 구조를 보고 싶다면 평일 오전이 더 좋습니다.',
    ),
    peakAvoidance: text(
      '晚餐时段和节假日主街人流明显，建议利用平行小巷与中段支路错峰穿行。',
      'Crowds rise on the main street during dinner hours and holidays; use parallel lanes and mid-block side streets to spread out.',
      '夕食時間や祝日はメインストリートの人流が増えます。並行する路地や中ほどの支路を使うと歩きやすいです。',
      '저녁 식사 시간과 공휴일에는 메인 거리에 인파가 늘어납니다. 평행 골목과 중간 지선을 활용하면 덜 붐빕니다.',
    ),
    bestFor: list(
      ['喜欢城市历史街区的人', '夜逛和小吃爱好者', '想把步行、购物、轻餐合并的人'],
      ['Visitors who enjoy historic urban streets', 'Evening strollers and snack seekers', 'Travellers combining walking, shopping and light dining'],
      ['歴史ある都市街区が好きな人', '夜歩きや軽食が好きな人', '散策・買い物・軽食をまとめたい人'],
      ['역사적 도심 거리를 좋아하는 사람', '야간 산책과 간식 탐방객', '걷기·쇼핑·가벼운 식사를 함께 하고 싶은 사람'],
    ),
    photoSpots: list(
      ['石板路与街灯透视', '骑楼与招牌层次', '巷口回望主街人流'],
      ['Stone paving under streetlights', 'Layered facades and signage', 'Looking back toward the main street from lane openings'],
      ['石畳と街灯の遠近感', '騎楼と看板の重なり', '路地口から主街を振り返る視点'],
      ['석판길과 가로등 원근감', '아케이드와 간판 레이어', '골목 입구에서 메인 거리를 돌아보는 시점'],
    ),
    nearbyDining: list(
      ['御街沿线小吃与杭帮菜', '清河坊传统点心', '老城咖啡与夜宵'],
      ['Snacks and Hangzhou dishes along the street', 'Traditional pastries in Qinghefang', 'Old-city cafes and late-night bites'],
      ['御街沿いの軽食と杭州料理', '清河坊の伝統菓子', '旧市街のカフェと夜食'],
      ['어가 일대 간식과 항저우 요리', '칭허팡 전통 디저트', '구시가지 카페와 야식'],
    ),
    restrooms: text(
      '主街商业节点与游客服务点更容易找到厕所，晚间建议不要等到离开街区再找。',
      'Restrooms are easier to find at major retail nodes and visitor services; at night, use one before you leave the main street.',
      'メインストリートの商業拠点や案内所で見つけやすいです。夜は街区を出る前に済ませておくと安心です。',
      '메인 거리 상업 거점과 관광안내 지점에서 찾기 쉽습니다. 밤에는 거리 밖으로 나가기 전에 먼저 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '这是典型轻装步行街区，不建议携带大件行李边逛边看；购物后再回酒店更舒适。',
      'This is a classic light-bag walking district; large luggage gets in the way, so it is more comfortable to return to your hotel after shopping.',
      '身軽に歩くのに向いた街区で、大きな荷物を引きながらの散策には不向きです。買い物後にホテルへ戻る流れが快適です。',
      '가볍게 걷기에 맞는 거리라 큰 짐을 끌고 둘러보는 데는 적합하지 않습니다. 쇼핑 후 호텔로 돌아가는 흐름이 더 편합니다.',
    ),
    rainyPlan: text(
      '小雨仍可逛，但体验会从“看街”转为“找店”；持续大雨更适合把它当作室内吃喝补给线。',
      'It remains workable in light rain, but the experience shifts from street-viewing to venue-hopping; in sustained rain, treat it more as an indoor food and refreshment corridor.',
      '小雨ならまだ歩けますが、体験は「街を見る」より「店をつなぐ」寄りになります。強い雨なら屋内補給ラインとして使う方が合っています。',
      '가벼운 비에는 여전히 걸을 수 있지만, 거리 감상보다 가게를 이어 다니는 경험으로 바뀝니다. 계속 큰비가 오면 실내 먹거리 보급선처럼 쓰는 편이 낫습니다.',
    ),
    languageService: text(
      '主街大店与游客节点相对容易沟通，小店与夜宵摊位仍以中文为主。',
      'Larger stores and visitor nodes on the main street are easier to navigate, while smaller shops and late-night stalls remain Chinese-first.',
      'メインストリートの大きめの店や観光拠点は比較的やり取りしやすい一方、小さな店や夜食屋台は中国語中心です。',
      '메인 거리의 큰 매장과 관광 거점은 비교적 소통이 쉽지만, 작은 가게와 야식 노점은 중국어 중심입니다.',
    ),
  },
  xianghu: {
    duration: text(
      '建议安排 2.5 至 4 小时；若加入游船、骑行或看日落，可做半天慢游。',
      'Allow 2.5 to 4 hours, or half a day if adding boating, cycling or a sunset stay.',
      '2.5〜4時間が目安。遊船、サイクリング、夕景まで入れるなら半日散策に向いています。',
      '2.5~4시간 정도가 적당하며, 유람선이나 자전거, 일몰까지 넣으면 반나절 슬로우 트립이 좋습니다.',
    ),
    bestArrival: text(
      '上午或傍晚到达都合适，若以拍照为主，日落前后一小时最漂亮。',
      'Morning and late afternoon both work; for photography, the hour around sunset is the most flattering.',
      '午前でも夕方でも回れますが、写真重視なら日没前後1時間が最もきれいです。',
      '오전이나 늦은 오후 모두 좋지만, 사진이 목적이면 일몰 전후 1시간이 가장 아름답습니다.',
    ),
    peakAvoidance: text(
      '节假日午后亲水平台和热门草坡会聚集，建议往更开阔的湖岸支线分流。',
      'On holiday afternoons, waterside platforms and popular lawns crowd quickly; spread out toward the broader side shorelines.',
      '祝日の午後は親水デッキや人気の芝生に人が集まります。より開けた湖岸の支線へ分散すると快適です。',
      '공휴일 오후에는 친수 플랫폼과 인기 잔디 경사면에 인파가 모입니다. 더 넓은 호안 지선으로 분산하는 편이 좋습니다.',
    ),
    bestFor: list(
      ['想找更安静湖景的人', '情侣、家庭和慢跑骑行人群', '不赶景点、重氛围的半日放松'],
      ['Visitors seeking a quieter lake scene', 'Couples, families, joggers and cyclists', 'Half-day relaxed itineraries where atmosphere matters more than checklists'],
      ['より静かな湖景を求める人', 'カップル、家族、ランニングや自転車の人', '名所数より雰囲気重視の半日リラックス'],
      ['더 조용한 호수 풍경을 찾는 사람', '커플, 가족, 러닝·자전거 이용자', '명소 체크보다 분위기를 중시하는 반나절 휴식'],
    ),
    photoSpots: list(
      ['开阔湖面与栈道', '草坡与远山层次', '傍晚天色倒影'],
      ['Open water with boardwalks', 'Layered lawns and distant hills', 'Evening sky reflections'],
      ['広い湖面とデッキ', '芝生斜面と遠山の重なり', '夕空の反射'],
      ['넓은 수면과 데크', '잔디 경사와 먼 산 레이어', '저녁 하늘 반사'],
    ),
    nearbyDining: list(
      ['湖区周边简餐与茶饮', '湘湖慢生活餐厅', '适合看日落后的晚餐点'],
      ['Tea and casual dining around the lake', 'Relaxed Xianghu restaurants', 'Dinner spots that work after sunset'],
      ['湖周辺の軽食とティー', '湘湖のゆったり系レストラン', '夕景のあとに使いやすい夕食スポット'],
      ['호수 주변 간단식과 차', '샹후의 느긋한 식당', '일몰 후 가기 좋은 저녁 장소'],
    ),
    restrooms: text(
      '游客中心、亲水节点与主要休闲区附近通常有厕所，若走长线环湖，建议在每个服务点顺手补给。',
      'Restrooms are usually near the visitor centre, waterside nodes and major leisure zones; on longer lakeside loops, use each service point as you pass.',
      '案内所、親水スポット、主要なレジャー区付近にあることが多いです。長めに周遊するならサービス拠点ごとに使っておくと安心です。',
      '안내소, 친수 지점, 주요 레저 구역 근처에 보통 있습니다. 길게 호숫가를 돌 계획이면 서비스 거점마다 이용하는 편이 좋습니다.',
    ),
    storage: text(
      '适合轻装慢走或骑行，若带野餐物和儿童用品可保留小件，大箱行李不建议带入湖岸线。',
      'This area suits light walking or cycling; picnic items and children’s essentials are fine, but large rolling luggage is not recommended on the lake route.',
      '身軽な散歩や自転車向きです。ピクニック用品や子ども用の小物は問題ありませんが、大きな荷物は湖岸線には向きません。',
      '가볍게 걷거나 자전거 타기에 적합합니다. 피크닉 용품이나 아이 물품은 괜찮지만 큰 캐리어는 호숫가 동선에 맞지 않습니다.',
    ),
    rainyPlan: text(
      '小雨可保留短线水岸散步，但风雨明显时湖岸停留会迅速变得不舒适，建议缩成餐饮或室内节点。',
      'Light rain still allows a short waterside walk, but once wind and rain rise the lakeshore becomes uncomfortable quickly; then reduce it to dining or indoor stops.',
      '小雨なら短い水辺散策は可能ですが、風雨が強まると快適さが一気に下がります。その場合は食事や屋内スポット中心に切り替えてください。',
      '가벼운 비에는 짧은 수변 산책이 가능하지만, 바람과 비가 강해지면 호숫가 체류가 금방 불편해집니다. 그때는 식사나 실내 거점 위주로 줄이세요.',
    ),
    languageService: text(
      '主景观节点导视通常够用，但沿湖分散区域仍更适合依赖地图导航。',
      'Wayfinding at the main scenic nodes is usually sufficient, but the more spread-out lakeside areas are easier to handle with map navigation.',
      '主な景観ノードの案内は比較的使えますが、湖沿いの分散区間は地図ナビ頼みの方が安心です。',
      '주요 경관 거점 안내는 비교적 충분하지만, 호숫가로 흩어진 구간은 지도 내비게이션을 쓰는 편이 더 좋습니다.',
    ),
  },
  'qiandao-lake': {
    duration: text(
      '若进入核心游船线路，建议至少预留 6 至 8 小时；若含往返交通，基本按一整天看待。',
      'For the core boat routes, reserve at least 6 to 8 hours; with round-trip transit, treat it as a full-day trip.',
      '主要な遊船ルートに入るなら6〜8時間以上を確保してください。往復移動込みなら、ほぼ1日コースです。',
      '핵심 유람선 노선에 들어가면 최소 6~8시간이 필요하며, 왕복 이동까지 고려하면 사실상 하루 일정입니다.',
    ),
    bestArrival: text(
      '建议按首班或较早船班规划，提前 30 至 45 分钟到码头更稳妥。',
      'Plan around the first or an early boat departure, arriving at the pier 30 to 45 minutes in advance.',
      '始発または早めの船便に合わせ、桟橋へ30〜45分前に着くのが安全です。',
      '첫 배나 이른 배편 기준으로 계획하고, 선착장에는 30~45분 먼저 도착하는 편이 안전합니다.',
    ),
    peakAvoidance: text(
      '节假日午后补位船班、返程时段和热门岛点最容易排队，若能早出早回体验会差很多。',
      'Holiday afternoon backup sailings, return windows and the most popular islands queue the hardest; starting early changes the experience considerably.',
      '祝日の午後の増便、帰りの時間帯、人気の島スポットは特に並びます。早く出て早めに戻るだけでも体感がかなり変わります。',
      '공휴일 오후 추가 배편, 귀환 시간대, 인기 섬 포인트에서 대기가 가장 큽니다. 일찍 출발하고 일찍 돌아오기만 해도 체감이 크게 달라집니다.',
    ),
    bestFor: list(
      ['计划整天出游的人', '喜欢湖岛与乘船体验的游客', '适合家庭、团队和外地游客专程前往'],
      ['Visitors planning a full-day outing', 'Travellers who enjoy islands and boat journeys', 'Families, groups and out-of-town visitors making a dedicated trip'],
      ['1日しっかり出かけたい人', '湖島と乗船体験が好きな人', '家族、グループ、遠方からの専程旅行向き'],
      ['하루 일정으로 나들이하려는 사람', '호수·섬과 승선 체험을 좋아하는 여행자', '가족, 단체, 외지 방문객이 전용 일정으로 가기 좋은 곳'],
    ),
    photoSpots: list(
      ['码头远望群岛', '航行中层层湖岛线', '登高后俯看湖面与船迹'],
      ['Island clusters seen from the pier', 'Layered islands from the boat', 'Elevated views over water and boat wakes'],
      ['桟橋から望む島々', '航行中に重なる湖島の線', '高所から俯瞰する湖面と航跡'],
      ['선착장에서 보는 군도', '항해 중 겹쳐지는 호수 섬 선형', '높은 곳에서 내려다보는 수면과 배 자취'],
    ),
    nearbyDining: list(
      ['码头与游客中心快餐', '千岛湖镇鱼头与本地菜', '返程前补给型餐饮'],
      ['Pier and visitor-centre fast dining', 'Fish-head and local dishes in Qiandao Lake town', 'Refuel stops before the return trip'],
      ['桟橋や案内所の軽食', '千島湖鎮の魚頭料理と郷土料理', '帰路前の補給向け飲食'],
      ['선착장과 안내소 패스트 다이닝', '첸다오후 진의 생선머리 요리와 현지식', '귀환 전 보급형 식당'],
    ),
    restrooms: text(
      '码头、游客中心和主要岛点一般都设有厕所，但船上与排队期间弹性小，建议上船前先解决。',
      'Restrooms are generally available at the pier, visitor centre and main islands, but flexibility drops once you are in boarding queues or on the boat, so go before you board.',
      '桟橋、案内所、主要な島ではトイレを見つけやすいですが、乗船列や船上では自由度が下がります。乗る前に済ませておくのが安心です。',
      '선착장, 안내소, 주요 섬에는 대체로 화장실이 있지만, 승선 대기열과 배 위에서는 유동성이 떨어집니다. 탑승 전에 미리 이용하세요.',
    ),
    storage: text(
      '游船一日线建议只带随身小包、防晒和饮水；大件行李最好留在酒店或镇区交通点。',
      'For full-day boat routes, carry only a small bag, water and sun protection; large luggage is best left at your hotel or in town.',
      '1日遊船ルートでは小さな手荷物、飲料、日除け程度がおすすめです。大きな荷物はホテルや町側の交通拠点に置いてください。',
      '하루 유람선 코스는 작은 가방, 물, 자외선 대비 정도만 챙기는 편이 좋습니다. 큰 짐은 호텔이나 시내 교통 거점에 두세요.',
    ),
    rainyPlan: text(
      '阴天对湖景影响不大，但大风大雨会直接影响船班与岛线体验，出发前务必查看停航或减班公告。',
      'Overcast skies are manageable, but strong wind and heavy rain directly affect sailings and island routes; always check suspension or reduced-service notices before departure.',
      '曇天は大きな問題ではありませんが、強風や大雨は船便と島ルートに直結します。出発前に欠航・減便告知を必ず確認してください。',
      '흐린 날은 큰 문제가 아니지만, 강풍과 큰비는 배편과 섬 노선에 직접 영향을 줍니다. 출발 전 결항·감편 공지를 꼭 확인하세요.',
    ),
    languageService: text(
      '交通、乘船和岛线判断比普通景点更依赖清晰信息，国际游客最好提前保存船班、码头与返程时间截图。',
      'Compared with typical city sights, transport and boat routing demand clearer information; international visitors should save boat times, pier details and return windows in advance.',
      '一般的な市内観光よりも、交通・乗船・島ルートの判断が重要です。船便、桟橋、帰り時間のスクリーンショットを事前保存しておくのがおすすめです。',
      '일반 시내 명소보다 교통·승선·섬 노선 판단이 더 중요합니다. 배 시간표, 선착장, 귀환 시간 스크린샷을 미리 저장해 두는 편이 좋습니다.',
    ),
  },
}

export const getPracticalVisitGuide = (spotId: string) => practicalGuides[spotId] ?? null
